### ISSUE TITLE
Errno 10061 - No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by dickinsonjl** [joeferraro/MavensMate#143]
Error when creating new project. 

Windows 7 64bit.

Using MavensMate v3.2.2 on SublimeText 3 build 3056.

Corporate environment. Firewall, antivirus, I have Admin privileges on local machine.

Log level set to DEBUG:
```

============================================
========== NEW OPERATION REQUESTED =========
============================================

new_project
{u'username': u'removed@details.com', u'project_name': u'My First Mavensmate SF project', u'package': {u'StaticResource': u'*', u'ApexTrigger': u'*', u'ApexComponent': u'*', u'ApexClass': u'*', u'ApexPage': u'*'}, u'org_url': u'', u'org_type': u'sandbox', 'client': 'SUBLIME_TEXT_3', 'ui': False, u'workspace': u'U:\\workspace', u'action': u'new', 'operation': 'new_project', u'password': u'passwordRemoved', u'subscription': [u'ApexClass', u'ApexComponent', u'ApexPage', u'ApexTrigger', u'CustomObject', u'Profile', u'StaticResource']}

============================================
>>>> getting settings
28.0
28.0
new_project
sending to (https://test.salesforce.com/services/Soap/u/28.0)
message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="urn:partner.soap.sforce.com" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <ns1:Body>
      <ns0:login>
         <ns0:username>removed@details.com</ns0:username>
         <ns0:password>passwordRemoved</ns0:password>
      </ns0:login>
   </ns1:Body>
</SOAP-ENV:Envelope>
headers = {'SOAPAction': u'""', 'Content-Type': 'text/xml; charset=utf-8', u'User-Agent': u'MavensMate'}
[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_project.py", line 103, in retrieve_and_write_to_disk
    self.sfdc_client = MavensMateClient(credentials={"username":self.username,"password":self.password,"org_type":self.org_type,"org_url":self.org_url})
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_client.py", line 88, in __init__
    self.login()
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_client.py", line 100, in login
    result = self.pclient.login(self.username, self.password, '')
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\sforce\base.py", line 490, in login
    result = self._sforce.service.login(username, password + token)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\client.py", line 602, in invoke
    result = self.send(soapenv)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\client.py", line 637, in send
    reply = transport.send(request)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\transport\http.py", line 77, in send
    fp = self.u2open(u2request)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\transport\http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
Traceback (most recent call last):
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_project.py", line 103, in retrieve_and_write_to_disk
    self.sfdc_client = MavensMateClient(credentials={"username":self.username,"password":self.password,"org_type":self.org_type,"org_url":self.org_url})
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_client.py", line 88, in __init__
    self.login()
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_client.py", line 100, in login
    result = self.pclient.login(self.username, self.password, '')
  File "C:\Users\dickinsonjl\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\sforce\base.py", line 490, in login
    result = self._sforce.service.login(username, password + token)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\client.py", line 602, in invoke
    result = self.send(soapenv)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\client.py", line 637, in send
    reply = transport.send(request)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\transport\http.py", line 77, in send
    fp = self.u2open(u2request)
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\suds-0.4-py2.7.egg\suds\transport\http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
[ENVIRONMENT]: 

```

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
