### ISSUE TITLE
MavensMate/lib/mm_interface.py", line 491, in handle_result

### ISSUE THREAD

**Issue by lookingcloudy** [joeferraro/MavensMate#162]
Getting this when trying to refresh project from server:
```
[MAVENSMATE] executing mm terminal call:
/Applications/MavensMate.app/Contents/Resources/mm/mm -o refresh -c SUBLIME_TEXT_3
{"directories": ["/Users/brad/workspaces/BFC/SFDC/ITGC-Terminations2"], "project_name": "ITGC-Terminations2", "files": [], "workspace": "/Users/brad/workspaces/BFC/SFDC"}
[MAVENSMATE] response from mm: {"body": "Refresh Completed Successfully", "body_type": "text", "success": true, "time": "6.598977088928223"}

Traceback (most recent call last):
  File "/Users/brad/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/mm_interface.py", line 480, in handle_result
    util.clear_marked_line_numbers()
TypeError: clear_marked_line_numbers() missing 1 required positional argument: 'view'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brad/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/threads.py", line 144, in <lambda>
    sublime.set_timeout(lambda: self.run(i), 50)
  File "/Users/brad/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/threads.py", line 115, in run
    self.thread.callback(self.thread.operation, self.thread.process_id, self.thread.printer, self.thread.result, self.thread)
  File "/Users/brad/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/mm_interface.py", line 491, in handle_result
    printer.write('\n[RESPONSE FROM MAVENSMATE]: '+result+'\n')
TypeError: Can't convert 'dict' object to str implicitly
```

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
