### ISSUE TITLE
3.3.5 Win8.1 - Compile Error

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate#187]
> Operation: Compiling Project
> Timestamp: Mon, 27 Jan 2014 10:11:34
> Result: [OPERATION FAILED]:An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.

Sample from log (this was repeated many times):

> [MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py", line 336, in main
    r.execute()
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py", line 100, in execute
    requested_function()
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py", line 140, in compile_selected_metadata
    print config.connection.project.compile_selected_metadata(self.payload)
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_project.py", line 374, in compile_selected_metadata
    result = self.sfdc_client.compile_with_tooling_api(files, container_id)
  File "C:\Users\Luke\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\mm_client.py", line 458, in compile_with_tooling_api
    r.raise_for_status()
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\requests-1.2.3-py2.7.egg\requests\models.py", line 683, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found

Compile actually turned out to be successful after checking the files on the server. I'm curious as to what actually failed.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
