### ISSUE TITLE
Creating a new project behind a proxy gets a 501 Server Error: Not Implemented error

### ISSUE THREAD

**Issue by zackshank** [joeferraro/MavensMate#188]
Hello,

When I am creating a new project, I am able to look at the Project Metadata but when I try to press "Create Project", I get a 501 Server Error: Not Implemented message. I have added my details and log below. Any help anyone has to offer is greatly appreciated. Thank you for your help!

OS: Mac OS X 10.9.1
Sublime Text 3 build 3059
mavensmate.app Version 0.37.0

Log:
```
Starting new HTTP connection (1): 127.0.0.1
"GET https://na15.salesforce.com/services/data/v28.0/tooling/query/?q=Select+Id+from+MetadataContainer+Where+Name+%3D+%27MavensMate-005i0000002ORFUAA4%27 HTTP/1.1" 501 3587
[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 115, in retrieve_and_write_to_disk
  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 1810, in __put_base_config
  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 1765, in __put_settings_file
  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_client", line 326, in get_metadata_container_id
  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/requests.models", line 638, in raise_for_status
HTTPError: 501 Server Error: Not Implemented




---------------------
RESPONDING TO REQUEST
---------------------


{"body": "501 Server Error: Not Implemented", "body_type": "text", "success": false}
```

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
