### ISSUE TITLE
Create Resource Bundle on Windows

### ISSUE THREAD

**Issue by mattaGIT** [joeferraro/MavensMate#198]
Hey Joe,

I have never been able to get resource bundles to work until recently on my windows desktop. My colleagues have this same issue. I recently fixed it and wanted to forward you the solution.

*Setup*
OS: Windows 7
MM:3.3.5
ST: 3

Creating resource bundles from a static resource that is a zipped .resource file resulted in:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "C:\Users\matt\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mavensmate.py", line 1152, in run
    resource_bundle.create(self, files) 
  File "C:\Users\matt\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\resource_bundle.py", line 52, in create
    fz = zipfile.ZipFile(f, 'r')
  File "./zipfile.py", line 933, in __init__
  File "./zipfile.py", line 974, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 524, in run_
    return self.run(**args)
  File "C:\Users\matt\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mavensmate.py", line 1152, in run
    resource_bundle.create(self, files) 
  File "C:\Users\matt\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\resource_bundle.py", line 52, in create
    fz = zipfile.ZipFile(f, 'r')
  File "./zipfile.py", line 933, in __init__
  File "./zipfile.py", line 974, in _RealGetContents
zipfile.BadZipFile: File is not a zip file
```

Error was due to the version of zipfile.py packaged with mavens. Installing 2.7.6 resolves the issue. If you force mavensmate to use it instead of the packaged pythong:
```
    //(advanced users only) set to location of your python 2.7 install (mm_debug_mode must be set to true)
    "mm_python_location": "C:\\Python27\\python.exe",
```
    //(advanced users only) set to true if you want to use system python (mm_python_location must be set)
    "mm_debug_mode": true,

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
