### ISSUE TITLE
400 Client Error: Bad Request (continued...)

### ISSUE THREAD

**Issue by kennesk** [joeferraro/MavensMate#220]
I have reviewed the other issues regarding 400 Client Error when trying to create a new project. I still have the issues and have not been able to successfully create a project. My details:
- Windows 7
- already had GIT
- installed Sublime Text 3
- installed Mavensmate
- uninstalled above
- rebooted
- reinstalled
- upgraded Mavesmate
- I've set the API version for User setting to 28.0 and 29.0
- I have several Salesforce orgs (Developer, Sandbox) and I am a System Admin on all of them
- the Tooling API WSDL in Salesforce says it is v29.0

I get a package created that has:
- all the correct src files
- a metadata.zip file with all the correct files in it
- a sublime-project file
- a package.xml file
- an empty config folder

My log file says:
"GET https://na15.salesforce.com/services/data/v29.0/tooling/query/?q=Select+Id+from+MetadataContainer+Where+Name+%3D+%27MavensMate-005i0000001vuesAAA%27 HTTP/1.1" 400 691
[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\kennedsa\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 118, in retrieve_and_write_to_disk
    self.__put_base_config()
  File "C:\Users\kennedsa\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 1019, in __put_base_config
    self.put_settings_file()
  File "C:\Users\kennedsa\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 944, in put_settings_file
    settings['metadata_container'] = self.sfdc_client.get_metadata_container_id()
  File "C:\Users\kennedsa\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\sfdc_client.py", line 348, in get_metadata_container_id
    r.raise_for_status()
  File "C:\Program Files (x86)\MavensMate\App\lib\site-packages\requests-1.2.3-py2.7.egg\requests\models.py", line 683, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request

---------------------
result from command execution
{"body": "400 Client Error: Bad Request", "body_type": "text", "success": false}
<type 'str'>
---------------------

Any help would be greatly appreciated.
Thanks.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
