### ISSUE TITLE
Unable to save files to server.

### ISSUE THREAD

**Issue by Stubbs** [joeferraro/MavensMate#232]
Since yesterday (Feb 27th) I haven't been able to save files to Salesforce with the following error on the Sublime console:

```
Writing file /Users/stu/Projects/WANdisco Sandbox 2/src/components/SupportWelcomeLetterDetails.component with encoding UTF-8 (atomic)
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'context': <sublime.View object at 0x10d1368d0>, 'params': {'files': ['/Users/stu/Projects/WANdisco Sandbox 2/src/components/SupportWelcomeLetterDetails.component']}}
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: /Applications/MavensMate.app/Contents/Resources/mm/mm -c SUBLIME_TEXT_3 -o compile
[MAVENSMATE]: {"workspace": "/Users/stu/Projects", "project_name": "WANdisco Sandbox 2", "files": ["/Users/stu/Projects/WANdisco Sandbox 2/src/components/SupportWelcomeLetterDetails.component"]}
[MAVENSMATE]: response from mm: 
[MAVENSMATE]: Issue handling compile result
Exception in thread Thread-47:
Traceback (most recent call last):
  File "X/json/scanner.py", line 30, in _scan_once
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X/json/decoder.py", line 368, in raw_decode
  File "X/json/scanner.py", line 32, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stu/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/mm_interface.py", line 360, in compile_callback
    result = json.loads(result)
  File "X/json/__init__.py", line 309, in loads
  File "X/json/decoder.py", line 352, in decode
  File "X/json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "/Users/stu/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/mm_interface.py", line 324, in run
    compile_callback(self, response_body)
  File "/Users/stu/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/mm_interface.py", line 371, in compile_callback
    debug(e.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

I've tried refreshing the projects meta data & creating a brand new project from scratch with a new token, but I get the same problem.

**Comment by joeferraro** [comment]
this has been resolved in the upcoming release
