### ISSUE TITLE
behind firewall, receiving "MaxRetryError(\"HTTPSConnectionPool(host= error...

### ISSUE THREAD

**Issue by kolansuresh** [joeferraro/MavensMate#265]
All of the classes, triggers and components are being downloaded...except that it dies with following error message....

Starting new HTTPS connection (1): removed--dev02.cs10.my.salesforce.com
[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\kolred01\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\commands\project.py", line 38, in execute
    result = config.project.retrieve_and_write_to_disk()
  File "C:\Users\kolred01\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 141, in retrieve_and_write_to_disk
    return util.generate_error_response(e.message)
  File "C:\Users\kolred01\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\util.py", line 831, in generate_error_response
    return json.dumps(res)
  File "C:\Program Files (x86)\MavensMate\App\lib\json\__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "C:\Program Files (x86)\MavensMate\App\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files (x86)\MavensMate\App\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Program Files (x86)\MavensMate\App\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: MaxRetryError("HTTPSConnectionPool(host='removed--dev02.cs10.my.salesforce.com', port=443): Max retries exceeded with url: /services/data/v28.0/tooling/query/?q=Select+Id+from+MetadataContainer+Where+Name+%3D+%27MavensMate-005J0000001MmJbIAK%27 (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)",) is not JSON serializable

---------------------
result from command execution
{"body": "MaxRetryError(\"HTTPSConnectionPool(host='removed--dev02.cs10.my.salesforce.com', port=443): Max retries exceeded with url: /services/data/v28.0/tooling/query/?q=Select+Id+from+MetadataContainer+Where+Name+%3D+%27MavensMate-005J0000001MmJbIAK%27 (Caused by <class 'socket.error'>: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond)\",) is not JSON serializable", "body_type": "text", "success": false}
<type 'str'>

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
