### ISSUE TITLE
Cannot create project from existing git checkout

### ISSUE THREAD

**Issue by musmuris** [joeferraro/MavensMate#274]
I'm on Windows and trying to create project from an existing git checkout.  The checkout isn't under where mavensmate projects go (if it is then I get Destination path 'c:\gitwork\salesforce\CORE-Salesforce' already exists).

The following error gets logged - plus it mucks up the checkout so that git doesn't recognise it any more and I have to checkout.again 

[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\nigel.morse\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 114, in retrieve_and_write_to_disk
    shutil.move(self.directory, config.connection.workspace)
  File "C:\Program Files (x86)\MavensMate\App\lib\shutil.py", line 299, in move
    rmtree(src)
  File "C:\Program Files (x86)\MavensMate\App\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files (x86)\MavensMate\App\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files (x86)\MavensMate\App\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Program Files (x86)\MavensMate\App\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Program Files (x86)\MavensMate\App\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: u'C:\\gitwork\\CORE-Salesforce\\.git\\objects\\00\\91ea712bf44e224485f74338576970e578b6e7'

---------------------
result from command execution
{"body": "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.", "body_type": "text", "success": false}
<type 'str'>
---------------------

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
