### ISSUE TITLE
64-bit Windows 8 cannot connect from behind proxy

### ISSUE THREAD

**Issue by trludewig** [joeferraro/MavensMate#370]
Do we think that MavensMate is in fact able to connect from behind a proxy from a 64-bit Windows 8 machine?  I've tried setting the proxy tons of ways and keep getting a connection error. Do I need a trailing / or anything else?  

	"mm_http_proxy" : "http:\/\/myusername:pwd@server.com:8080",
	"mm_https_proxy" : "http:\/\/myusername:pwd@server.com:8080",

Are these in fact bugs still?  

https://github.com/joeferraro/MavensMate/issues/191  
https://github.com/joeferraro/MavensMate-SublimeText/issues/375 

I'm using Sublime Build 3059 (64-bit) and MavensMate for Sublime Text v3.5.2.

Here is my log.

[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\tenley.ludewig\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 107, in retrieve_and_write_to_disk
    self.sfdc_client = MavensMateClient(credentials={"username":self.username,"password":self.password,"org_type":self.org_type,"org_url":self.org_url})
  File "C:\Users\tenley.ludewig\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\sfdc_client.py", line 90, in __init__
    self.login()
  File "C:\Users\tenley.ludewig\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\sfdc_client.py", line 102, in login
    result = self.pclient.login(self.username, self.password, '')
  File "C:\Users\tenley.ludewig\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\sforce\base.py", line 490, in login
    result = self._sforce.service.login(username, password + token)
  File "build\bdist.win32\egg\suds\client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "build\bdist.win32\egg\suds\client.py", line 602, in invoke
    result = self.send(soapenv)
  File "build\bdist.win32\egg\suds\client.py", line 637, in send
    reply = transport.send(request)
  File "build\bdist.win32\egg\suds\transport\http.py", line 77, in send
    fp = self.u2open(u2request)
  File "build\bdist.win32\egg\suds\transport\http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\Program Files (x86)\MavensMate\App\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
