### ISSUE TITLE
Unable to create project - Ubuntu 14

### ISSUE THREAD

**Issue by mrichmon12** [joeferraro/MavensMate#380]
Hi,

I have a brand new installation of Sublime Text 3 and Mavensmate (installed via Package Control) and I'm having trouble creating a new project. 

I get the following error: 

[OPERATION FAILED]: Could not find the mm executable. Please run MavensMate > Install/Update MavensMate API (mm) to install mm to your MavensMate for Sublime Text plugin directory.

If I follow what the message nothing happens on the UI, but I get some interesting messages in the Sublime Console.

[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
Traceback (most recent call last):
  File "./json/scanner.py", line 30, in _scan_once
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./json/decoder.py", line 368, in raw_decode
  File "./json/scanner.py", line 32, in _scan_once
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 526, in run_
    return self.run()
  File "/home/<redacted>/.config/sublime-text-3/Packages/MavensMate/mavensmate.py", line 1355, in run
    mm_releases = mm_installer.get_mm_releases()
  File "/home/<redacted>/.config/sublime-text-3/Packages/MavensMate/lib/mm_installer.py", line 94, in get_mm_releases
    return json.loads(releases)
  File "./json/__init__.py", line 319, in loads
  File "./json/decoder.py", line 352, in decode
  File "./json/decoder.py", line 370, in raw_decode
ValueError: No JSON object could be decoded

Not sure what is going on here, but I have tried to reinstall both Sublime Text and Mavensmate, but that didn't do anything. I have installed on Ubuntu before and never had issues like this.

Any ideas?

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
