### ISSUE TITLE
Polling timeout when Creating New Metadata Class

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#427]
mm: v.0.0.35-alpha1(node.js)
st3: node branch commit 0cd0e3a5a69bd802fba1cebccb5435b971d75f3f

polling seems to have some issues, it worked on a second try

log details
```
==================> executing command: new-metadata

2015-04-20T16:26:44.137Z - debug:   payload is: {"metadataTypeXmlName":"ApexClass","templateValues":{"api_name":"PWA_ImageMigrator"},"template":{"name":"Default","file_name":"ApexClass.cls","description":"The default template for an Apex Class","author":"MavensMate","params":[{"name":"api_name","description":"Apex Class API Name","default":"MyApexClass"}]}}
2015-04-20T16:26:44.137Z - debug:   command class is: NewMetadataCommand
2015-04-20T16:26:44.138Z - debug:   getting metadata type by name: ApexClass
2015-04-20T16:26:44.138Z - debug:    directoryName=classes, inFolder=false, metaFile=true, suffix=cls, xmlName=ApexClass
2015-04-20T16:26:44.139Z - debug:   deploying file: 
2015-04-20T16:26:44.139Z - debug:   initing package instance with subscription: 
2015-04-20T16:26:44.139Z - debug:    ApexClass=[PWA_ImageMigrator]
2015-04-20T16:26:44.140Z - debug:   serializing package:
2015-04-20T16:26:44.140Z - debug:    ApexClass=[PWA_ImageMigrator]
2015-04-20T16:26:44.142Z - debug:   writing package to path: /var/folders/cp/m0vszw1n2t3211rfv_2h91fw0000gn/T/mm_115320-7629-1t9kyrt/unpackaged/package.xml
2015-04-20T16:26:44.143Z - debug:   <?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>PWA_ImageMigrator</members>
		<name>ApexClass</name>
	</types>
	<version>33.0</version>
</Package>
2015-04-20T16:27:15.295Z - debug:   Error deploying new file to server
2015-04-20T16:27:15.295Z - debug:   Error: polling time out
    at poll [as _onTimeout] (/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/jsforce/lib/api/metadata.js:651:26)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
2015-04-20T16:27:15.296Z - debug:   response: 
2015-04-20T16:27:15.296Z - debug:    result=Could not create metadata, error=polling time out, stack=Error: polling time out
    at poll [as _onTimeout] (/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/jsforce/lib/api/metadata.js:651:26)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
2015-04-20T16:28:06.958Z - debug:
```

**Comment by joeferraro** [comment]
@ralphcallaway what is your `mm_timeout` setting out of curiosity?

**Comment by ralphcallaway** [comment]
@joeferraro it's at 60 currently, although I believe it was at 30 when i created this ticket
