### ISSUE TITLE
Polling Timeout / Response Parse Error Cleaning Project 

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#433]
mm: v.0.0.35-alpha1(node.js)
st3: node branch commit 0cd0e3a5a69bd802fba1cebccb5435b971d75f3f

cleaning project stalled out with no error or details

mavens mate console (stuck)
```
Operation: Cleaning Project
Timestamp: Mon, 20 Apr 2015 15:16:24
   Result: [       =]
```

mavens mate log 
```
==================> executing command: clean-project

2015-04-20T21:16:27.840Z - debug: payload is: undefined
2015-04-20T21:16:27.840Z - debug: command class is: CleanProjectCommand
2015-04-20T21:16:27.841Z - debug: initing package instance
2015-04-20T21:16:27.841Z - debug: deserializing: /<redacted>/src/package.xml
2015-04-20T21:16:27.843Z - debug: parsed package.xml to -->{"ApexClass":"*","ApexComponent":"*","ApexPage":"*","ApexTrigger":"*","StaticResource":"*"}
2015-04-20T21:16:27.843Z - debug: setting package subscription: 
2015-04-20T21:16:27.843Z - debug:  ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*, StaticResource=*
2015-04-20T21:16:27.844Z - debug: retrieving unpackaged: 
2015-04-20T21:16:27.844Z - debug:  ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*, StaticResource=*
```

sublime console
```
[MAVENSMATE]: Calling cli
[MAVENSMATE]: OPERATION: clean-project
[MAVENSMATE]: {'context': <MavensMate.mavensmate.CleanProjectCommand object at 0x10916b450>}
[MAVENSMATE]: mavensmate command: 
[MAVENSMATE]: ['/usr/local/bin/node', '/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/bin/mavensmate', '--headless', '-e', 'sublime', '--port', '55630', 'clean-project']
[MAVENSMATE]: /<project folder>
[MAVENSMATE] failed to send community activity
[MAVENSMATE]: response from mm: 

stream.js:94

      throw er; // Unhandled stream error in pipe.

            ^

Error: polling time out

    at poll [as _onTimeout] (/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/jsforce/lib/api/metadata.js:651:26)

    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: 

stream.js:94

      throw er; // Unhandled stream error in pipe.

            ^

Error: polling time out

    at poll [as _onTimeout] (/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/node_modules/jsforce/lib/api/metadata.js:651:26)

    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

Traceback (most recent call last):
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/threads.py", line 144, in <lambda>
    sublime.set_timeout(lambda: self.run(i), 50)
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/threads.py", line 115, in run
    self.thread.callback(self.thread.operation, self.thread.process_id, self.thread.printer, self.thread.result, self.thread)
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/cli.py", line 324, in handle_result
    raise e
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/cli.py", line 320, in handle_result
    result_handler.execute()
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/response_handler.py", line 41, in execute
    self.__print_error()
  File "/Users/ralphcallaway/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/response_handler.py", line 76, in __print_error
    msg = '[ERROR]: '+self.response.error
AttributeError: 'str' object has no attribute 'error'
reloading /Users/ralphcallaway/Documents/eclipse 3.7/mmlogs/mavensmate.log
```

**Comment by joeferraro** [comment]
do you have `mm_timeout` set?

**Comment by ralphcallaway** [comment]
not in my user settings, the package default settings have it set to 30

fyi, this worked on a second try, although this is the second time i've run across a polling error crashing things

**Comment by joeferraro** [comment]
hm. how big is the project? any chance the clean command would require more than 30 seconds?

**Comment by ralphcallaway** [comment]
it's a pretty mature org, i would not be surprised if it took longer than
30 seconds,

i would have assumed that the timeout was for a single call, is it actually
a command timeout?

On Mon, Apr 20, 2015 at 3:31 PM, Joe Ferraro <notifications@github.com>
wrote:

> hm. how big is the project? any chance the clean command would require
> more than 30 seconds?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate/issues/433#issuecomment-94574216>
> .
>



-- 
 *Ralph Callaway*
President & Principal Architect
*P:* (415) 763-5484
*Schedule a Meeting:*
meetme.so/callawaycloud
      [image: CCC Logo]

**Comment by joeferraro** [comment]
@ralphcallaway it's supposed to be for a single call, which is why this is odd behavior. i havent been unable to reproduce on my side

**Comment by joeferraro** [comment]
ok i just reproduced this by setting my `mm_timeout` to `1`

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate/commit/a5d0aafd57d29d503536e7d4d4f50cbcdd4e85f5 closes this issue
