### ISSUE TITLE
new-resource-bundle does not work

### ISSUE THREAD

**Issue by steals** [joeferraro/MavensMate#459]
When I try to create Resource bundle through ST plugin I get following log:
```
OPERATION: new-resource-bundle
{'context': <MavensMate.mavensmate.NewResourceBundleCommand object at 0x103474510>, 'flags': ['/Users/steals/Workspaces/MavensMate/Angular Test/src/staticresources/AngularAndBootstrap.resource'], 'message': 'Creating resource bundle...'}
http://localhost:54901/execute?command=new-resource-bundle&async=1&pid=f958fec0-2587-11e5-b737-d1a4deb6494f
{'result': {'message': 'Resource bundle(s) successfully created'}, 'complete': True, 'operation': 'new-resource-bundle', 'id': '31587cc0-258c-11e5-991a-a30b6532c237'}
```
But resource-bundle does not creating.

If I run "mavensmate new-resource-boundle" in console I get following errors:
```
/U/s/W/M/Angular Test ❯❯❯ mavensmate new-resource-bundle src/staticresources/AngularAndBootstrap.resource
Possibly unhandled TypeError: undefined is not a function
  at /usr/local/lib/node_modules/mavensmate/lib/mavensmate/project.js:176:34
  at tryCatch1 (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
  at Promise._callHandler (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
  at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromiseAt (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
  at Promise._settlePromises (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
  at Async._consumeFunctionBuffer (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
  at Async.consumeFunctionBuffer (/usr/local/lib/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
  at process._tickCallback (node.js:355:11)
```

**Comment by joeferraro** [comment]
@steals thanks for these reports. It'd be helpful if you could configure:

```
"mm_log_level": "SILLY",
"mm_log_location": "some/path"
```

so that mavensmate will generate debug logs. then paste these additional logs with your issue. thanks!

**Comment by steals** [comment]
Updated to master. Configured SILLY log level. https://gist.github.com/steals/34001e81b1491700d818

**Comment by steals** [comment]
Now it works. Thank you!
