### ISSUE TITLE
How can I create a Lightning app from MM?

### ISSUE THREAD

**Issue by ryanhuff** [joeferraro/MavensMate#569]
Trying to create a simple filename.app file and I get the error, "[ERROR]: Could not update lightning components: Cannot read property 'Id' of undefined"

Am I doing something dumb?

**Comment by joeferraro** [comment]
Hi, can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by ukoya** [comment]
OSX Yosemite 64 bits
mm plugin 1.0.6 on latest atom.io
mm app v0.0.10-beta5 (issue happens also on latest stable)
Steps : Modify a component/app and save
Log:
```
2015-10-15T14:06:08.072Z - error:  Error: Could not update lightning components: Cannot read property 'Id' of undefined
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/lightning.js:189:18
    at tryCatch1 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
    at Promise._settlePromises (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
    at Async._consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

**Comment by joeferraro** [comment]
does this happen with a brand new project?

**Comment by ukoya** [comment]
Good one, i just created a new one to test. The issue is gone now.

**Comment by joeferraro** [comment]
To help us better understand the issue, was the project in question created before the transition to mm-app? (in other words, was it a legacy project)

**Comment by ukoya** [comment]
It was a new project, but i did a deploy to this org and then updated my local project.

**Comment by joeferraro** [comment]
When you say you updated your local project, you did so via the "Edit Project" screen?

**Comment by ukoya** [comment]
Yes from the app not from
the editor

**Comment by dnalot** [comment]
Same thing here same scenario. Save Lightning JS controller created from Dev Console and can't update it.

**Comment by dnalot** [comment]
Deleting `config/.lightning` fixed it. I just followed the stack trace and looked for the `.id` reference.

**Comment by steals** [comment]
Also noticed the controllers/helpers/and other parts of Lightning component will not compile it they created after initial sync of mm project. (Clean Project works as workaround)
Steps to reproduce:
1) I create Lightning component in Dev console (just html part)
2) Sync it to mm project (update metadata + update project) 
3) Add a controller to that component in dev console and then sync it to mm project
4) Update the code of the controller and check if it saved to SF

**Comment by dnalot** [comment]
Thanks for making it reproducible @steals! I wasn't aware of the Clean Project command either.

**Comment by figosat** [comment]
Hi,
I installed an unmanaged package for my some lightning components dev, i get this where error when i try to save.

[ERROR]: Could not update lightning components: Cannot read property 'Id' of undefined.

Have any idea about this error. thks

**Comment by JPWallhorn** [comment]
Is there any update? I tried deleting the config/.lightning file but I still get the same error message.

**Comment by cemerson** [comment]
Seems to have worked for me (deleting config/.lighting). Very odd but least I'm past it.

**Comment by ankit1421** [comment]
Even after deleting the .lightning..I am getting this issue.

**Comment by cemerson** [comment]
Yeah I think I recall it being bit quirky like I had to exit/relaunch Sublime and/or reset some other stuff before it took ... but in the end just deleting that file did it for me.  Good luck!

**Comment by taffygoat** [comment]
I can't update xml file inside a lightning component bundle. I'm getting this error
