### ISSUE TITLE
Connection ETIMEOUT error

### ISSUE THREAD

**Issue by meghsmayur** [joeferraro/MavensMate#571]
Platform :  Windows 64bit
MavensMate plugin version : Version 7
MavensMate-app version: v0.0.10-beta4
Showing connection ETIMEOUT error when I am trying to create a new project. MavensMate App on windows.
![image](https://cloud.githubusercontent.com/assets/15013260/10335754/c22ec71a-6d10-11e5-8143-e69622c5d40b.png)
Don not know how to capture log. Pasted URL in browser and showing below error messages.

**Comment by meghsmayur** [comment]
getting following error message

TypeError: Cannot read property 'complete' of undefined
   at JobQueue.isJobComplete (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\job-queue.js:37:29)
   at UIServer.statusRequest (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\server.js:88:16)
   at Layer.handle [as handle_request] (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\layer.js:82:5)
   at next (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\route.js:100:13)
   at Route.dispatch (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\route.js:81:3)
   at Layer.handle [as handle_request] (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\layer.js:82:5)
   at C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:235:24
   at Function.proto.process_params (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:313:12)
   at C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:229:12
   at Function.match_layer (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:296:3)
   at next (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:190:10)
   at C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:192:16
   at Function.match_layer (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:296:3)
   at next (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:190:10)
   at C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:192:16
   at Function.match_layer (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\index.js:296:3)

**Comment by joeferraro** [comment]
Hi @meghsmayur, please update your issue according to the guidelines: https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

thanks!

**Comment by meghsmayur** [comment]
Updated..

**Comment by joeferraro** [comment]
@meghsmayur hi thanks very much. are you behind a firewall/proxy?

**Comment by meghsmayur** [comment]
Yes.. I am at my office network there is firewall but no proxy.

**Comment by meghsmayur** [comment]
Getting new error this time..
tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

**Comment by garyspencer** [comment]
Do you have a web server (or some other software) already listening on 80?

**Comment by meghsmayur** [comment]
Problem was with the firewall. Issue resolved.
