### ISSUE TITLE
mavensmate-app  error in edit project

### ISSUE THREAD

**Issue by francesco-rampoldi** [joeferraro/MavensMate#592]
Mavensmate App v 0.0.11-beta1  Error  in "Edit Project" function

TypeError: project.getDescribe is not a function
   at ViewHelper.getMetadataObjects (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\helper.js:84:27)
   at evalmachine.<anonymous>:302:1617
   at Object.tpl (evalmachine.<anonymous>:335:3)
   at compiled (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:658:18)
   at C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:598:20
   at compileFile (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:708:9)
   at View.renderFile [as engine] (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:589:12)
   at View.render (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\view.js:93:8)
   at EventEmitter.app.render (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\application.js:530:10)
   at ServerResponse.res.render (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\response.js:904:7)
   at ProjectController.edit (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\controllers\project.js:36:9)
   at UIServer.appRequestHandler (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\server.js:173:28)
   at Layer.handle [as handle_request] (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\layer.js:82:5)
   at next (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\route.js:100:13)
   at Route.dispatch (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\route.js:81:3)
   at Layer.handle [as handle_request] (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\layer.js:82:5)

**Comment by joeferraro** [comment]
@francesco-rampoldi can you clean your project to see whether that fixes your issue?

**Comment by francesco-rampoldi** [comment]
Tried to clean project, closed and reopened app.

Now error on “edit project” is:

TypeError: project.getDescribe is not a function
   at ViewHelper.getMetadataObjects (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\helper.js:84:27)
   at evalmachine.<anonymous>:302:1617
   at Object.tpl (evalmachine.<anonymous>:335:3)
   at compiled (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:658:18)
   at C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:598:20
   at C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:729:9
   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
