### ISSUE TITLE
bug at edit project

### ISSUE THREAD

**Issue by daniel-refahi** [joeferraro/MavensMate#595]
My password has expired and I'm trying to update the project with the new password but I'm getting this error message: 

TypeError: project.getDescribe is not a function
   at ViewHelper.getMetadataObjects (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\helper.js:84:27)
   at evalmachine.<anonymous>:302:1617
   at Object.tpl (evalmachine.<anonymous>:335:3)
   at compiled (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:658:18)
   at C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:598:20
   at C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:729:9
   at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by ralphcallaway** [comment]
that's a strange one, have you tried deleting and recreating the project to see if that works?

**Comment by daniel-refahi** [comment]
that's exactly what I did to fix it. :)

**Comment by zjeh** [comment]
I experienced the same thing this morning opening an existing project where the password had expired. I was able to fix it - tho by stubbornness or ignorance, i cannot say.

__*Steps to Recreate*__
mm-app win-x64 v0.0.10

* Menu >> Project >> Open Project - opens a localhost tab with error
>Error initializing project: INVALID_OPERATION_WITH_EXPIRED_PASSWORD: The users password has expired, you must call SetPassword before attempting any other API operations

* Login with browser and change password

* Menu >> Project >> Open Project - opens project home tab as usual

* Menu >> Project >> Edit Project - (to update new password) opens localhost error screen
>TypeError: project.getDescribe is not a function
>at ViewHelper.getMetadataObjects (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\helper.js:84:27)
>at evalmachine.<anonymous>:302:1617
>at Object.tpl (evalmachine.<anonymous>:335:3)
>at compiled (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:658:18)
>at C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:598:20
>at compileFile (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:708:9)
>at View.renderFile [as engine] (C:\Program Files\MavensMate\resources\app\node_modules\swig\lib\swig.js:589:12)
>at View.render (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\view.js:93:8)
>at EventEmitter.app.render (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\application.js:530:10)
>at ServerResponse.res.render (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\response.js:904:7)
>at ProjectController.edit (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\controllers\project.js:36:9)
>at UIServer.appRequestHandler (C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\ui\server.js:173:28)
>at Layer.handle [as handle_request] (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\layer.js:82:5)
>at next (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\route.js:100:13)
>at Route.dispatch (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\route.js:81:3)
>at Layer.handle [as handle_request] (C:\Program Files\MavensMate\resources\app\node_modules\express\lib\router\layer.js:82:5)

* Menu >> Project >> Open in Sublime - opens Fix Project tab where you can change password
  * after saving update, Sublime Text does not open; but you have a working project again

![fix_project](https://cloud.githubusercontent.com/assets/2139356/11508555/677c8252-9827-11e5-8575-b0e099bf6fb8.png)
