### ISSUE TITLE
Unable to Index Project Metadata

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#601]
app: v0.0.10
st3: v7.0.0-beta.1

Was trying to run the apex unit tests for a class and got an error `Invalid project metadata cache. Run Index Metadata command to reset the cache.` When I try to refresh the project cache I get the the an error `INVALID_TYPE: Cannot use: OpportunitySharingRules in this version`

mavensmate console (in example i repeated test run command after trying index metadata)
```
Operation: Indexing Metadata
Timestamp: Wed, 11 Nov 2015 23:04:22
   Result: [ERROR]: INVALID_TYPE: Cannot use: OpportunitySharingRules in this version
 
Operation: Running Apex unit test(s)...
Timestamp: Wed, 11 Nov 2015 23:08:41
   Result: [ERROR]: Invalid project metadata cache. Run Index Metadata command to reset the cache.                                                                          
```

st3 console
```
[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: index-metadata
[MAVENSMATE]: {'context': <MavensMate.mavensmate.IndexMetadataCommand object at 0x10d981110>}
[MAVENSMATE]: http://localhost:56248/execute?command=index-metadata&async=1&pid=N9FRIWX0ITLGRR9N76JKZ4W1WK70UNMH
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x10d5bacd0>
[MAVENSMATE]: {'stack': 'sf:INVALID_TYPE: INVALID_TYPE: Cannot use: OpportunitySharingRules in this version\n    at HttpApi.getError (/Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/http-api.js:240:13)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/http-api.js:85:22\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/promise/lib/core.js:33:15\n    at flush (/Applications/MavensMate.app/Contents/Resources/app/node_modules/asap/asap.js:27:13)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)', 'id': '3877ca30-8903-11e5-9abd-03fea1113833', 'operation': 'index-metadata', 'complete': True, 'error': 'INVALID_TYPE: Cannot use: OpportunitySharingRules in this version'}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'stack': 'sf:INVALID_TYPE: INVALID_TYPE: Cannot use: OpportunitySharingRules in this version\n    at HttpApi.getError (/Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/http-api.js:240:13)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/http-api.js:85:22\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/promise/lib/core.js:33:15\n    at flush (/Applications/MavensMate.app/Contents/Resources/app/node_modules/asap/asap.js:27:13)\n    at doNTCallback0 (node.js:416:9)\n    at process._tickCallback (node.js:345:13)', 'id': '3877ca30-8903-11e5-9abd-03fea1113833', 'operation': 'index-metadata', 'complete': True, 'error': 'INVALID_TYPE: Cannot use: OpportunitySharingRules in this version'}
[MAVENSMATE] skipped community activity
reloading /Users/ralphcallaway/Documents/eclipse 3.7/mmlogs/mavensmate.log
[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: run-tests
[MAVENSMATE]: {'message': 'Running Apex unit test(s)...', 'context': <MavensMate.mavensmate.RunAsyncApexTestsCommand object at 0x10d87edd0>, 'body': {'skipCoverage': True, 'tests': ['<redcated_test_class>']}}
[MAVENSMATE]: http://localhost:56248/execute?command=run-tests&async=1&pid=N9FRIWX0ITLGRR9N76JKZ4W1WK70UNMH
[MAVENSMATE]: posting to MavensMate:
[MAVENSMATE]: b'{"skipCoverage": true, "tests": ["<redacted_test_class>"]}'
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x10dc02f50>
[MAVENSMATE]: {'stack': 'Error: Invalid project metadata cache. Run Index Metadata command to reset the cache.\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/test.js:70:25\n    at arrayEach (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:1289:13)\n    at Function.<anonymous> (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:3345:13)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/test.js:67:9\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at ApexTest.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/test.js:58:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/unit-test/run-tests.js:41:12\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Command.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/unit-test/run-tests.js:24:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:380:21\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)', 'id': 'd2b54370-8903-11e5-9abd-03fea1113833', 'operation': 'run-tests', 'complete': True, 'error': 'Invalid project metadata cache. Run Index Metadata command to reset the cache.'}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'stack': 'Error: Invalid project metadata cache. Run Index Metadata command to reset the cache.\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/test.js:70:25\n    at arrayEach (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:1289:13)\n    at Function.<anonymous> (/Applications/MavensMate.app/Contents/Resources/app/node_modules/lodash/index.js:3345:13)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/test.js:67:9\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at ApexTest.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/test.js:58:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/unit-test/run-tests.js:41:12\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)\n    at new Promise (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)\n    at Command.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/commands/unit-test/run-tests.js:24:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/client.js:380:21\n    at tryCatch2 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)\n    at Promise._resolveFromResolver (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)', 'id': 'd2b54370-8903-11e5-9abd-03fea1113833', 'operation': 'run-tests', 'complete': True, 'error': 'Invalid project metadata cache. Run Index Metadata command to reset the cache.'}
[MAVENSMATE] skipped community activity
reloading /Users/ralphcallaway/Documents/eclipse 3.7/mmlogs/mavensmate.log
```

[mavensmate log](https://gist.github.com/ralphcallaway/189d15bfee47bd4dc7fb)

**Comment by ralphcallaway** [comment]
able to get this working by adjusting the metadata subscription list to just include the basic stuff, leaving open as in case we want to update index metadata to be more robust on handling this sort of error (but fine with me to close if it's not a priority)

also got the same error message when cleaning the project, which was also resolved after adjusting the metadata subscription list for the project
