### ISSUE TITLE
Unable to execute anonymous apex from Mavensmate App project.

### ISSUE THREAD

**Issue by nerdybeast** [joeferraro/MavensMate#602]
I am trying to run some anonymous apex after opening a project in the Mavensmate App but am receiving this error: `Could not create Trace Flags: LogType is required.` I'm not sure if I need to set a log type somewhere or what. Any help will be greatly appreciated.

I am running app version 0.0.10 on Windows. Here are the relevant logs:

```
2015-11-12T15:46:59.872Z - info: 

==================> executing command: start-logging

2015-11-12T15:46:59.872Z - info: executeCommandForProject payload is: null
2015-11-12T15:46:59.872Z - debug: command class is: StartLoggingCommand
2015-11-12T15:46:59.875Z - debug: attempting to start logging for: 
2015-11-12T15:46:59.875Z - debug:  0=005G0000003pal8IAA
2015-11-12T15:46:59.875Z - debug: expiring: 1447372019873
2015-11-12T15:47:00.200Z - debug: attempting to delete trace flags: 
2015-11-12T15:47:00.200Z - debug: 
2015-11-12T15:47:00.201Z - debug: deleted trace flags
2015-11-12T15:47:00.201Z - debug: 
2015-11-12T15:47:00.201Z - debug: attempting to create trace flags
2015-11-12T15:47:00.514Z - info: handling command result: 
2015-11-12T15:47:00.514Z - error:  Error: Could not create Trace Flags: LogType is required.: LogType
    at C:\Program Files\MavensMate\resources\app\node_modules\mavensmate\lib\mavensmate\sfdc-client.js:931:20
    at C:\Program Files\MavensMate\resources\app\node_modules\promise\lib\core.js:33:15
    at flush (C:\Program Files\MavensMate\resources\app\node_modules\asap\asap.js:27:13)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
```

**Comment by ralphcallaway** [comment]
it looks like there was a schema change around the trace flags used to get the logs (in this case for anon execute) with api version 35.0, if you're using that version you can work around this issue by changing to v34

got a patch going, but not sure when that will be released
