### ISSUE TITLE
Can't Install MavenMate API

### ISSUE THREAD

**Issue by thomasxhoban** [joeferraro/MavensMate#613]
I have looked at several postings and still can't solve me problem.  I'm trying to install MavenMate for the first time.  I installed (1) sublime Text onto Windows 8, (2) Sublime Text Package Control and (3) the MavensMate package. 

I'm getting a connection error shown in the console log at the bottom of this post when I try to install the MM API.  From the error message, I'm guessing that it is choking trying to connect to "https://api.github.com/repos/joeferraro/mm/releases".  I can download this using my browser so I don't know why this environment cannot connect.  If the connection failure is with some other url, can you give me a clue on how I determine this?  Also, can I assume the protocol is either HTTP or HTTPS in the event I need to speak to our network/firewall team.  

We do also have a proxy server and I plugged url with user/password/ip address into the MavenMate preferences.  It does not seem to help.

In the menu, I navigate to MavenMate->MavenMate API (mm)->Install MavenMate API (mm) version....   It then gives the error below.  Any help would be greatly appreciated.

Thanks

Below is the error output written to the console...

Traceback (most recent call last):
  File "./urllib/request.py", line 1248, in do_open
  File "./http/client.py", line 1065, in request
  File "./http/client.py", line 1103, in _send_request
  File "./http/client.py", line 1061, in endheaders
  File "./http/client.py", line 906, in _send_output
  File "./http/client.py", line 844, in send
  File "./http/client.py", line 1198, in connect
  File "./socket.py", line 435, in create_connection
  File "./socket.py", line 426, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 535, in run_
    return self.run()
  File "C:\Users\txh65\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mavensmate.py", line 1357, in run
    mm_releases = mm_installer.get_mm_releases()
  File "C:\Users\txh65\AppData\Roaming\Sublime Text 3\Packages\MavensMate\lib\mm_installer.py", line 93, in get_mm_releases
    releases = urllib.request.urlopen('https://api.github.com/repos/joeferraro/mm/releases').read().decode('utf-8')    
  File "./urllib/request.py", line 156, in urlopen
  File "./urllib/request.py", line 469, in open
  File "./urllib/request.py", line 487, in _open
  File "./urllib/request.py", line 447, in _call_chain
  File "./urllib/request.py", line 1283, in https_open
  File "./urllib/request.py", line 1251, in do_open
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

**Comment by ralphcallaway** [comment]
@thomasxhoban checkout https://github.com/joeferraro/MavensMate-SublimeText/issues/556 for instructions on installing this portion manually

you might also consider switching to v7 of the ST3 plugin (still in pre-release) which doesn't require this installer anymore, see `install_prereleases` in https://packagecontrol.io/docs/settings

closing for now, but reopen if that doesn't get you going
