### ISSUE TITLE
`npm test` throws "error: unknown option `--recursive'"

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#616]
v0.0.10

running npm test locally results in mocha throwing "error: unknown option `--recursive'" which halts test execution and prevents mocha from printing test results

this doesn't affect circle ci tests 

example run test 
```
➜  MavensMate git:(readme_updates) SALESFORCE_USERNAME=<redacted> SALESFORCE_PASSWORD="<redacted>" npm test           

> mavensmate@0.0.44-beta5 test /Users/ralphcallaway/MavensMate/MavensMate
> make test



  mavensmate apex-script
info: editor unlinked
    ✓ should create a new apex script
    ✓ should execute an apex script that fails to compile (497ms)
    ✓ should execute an apex script that compiles successfully (554ms)

  mavensmate checkpoints
    ✓ should add checkpoint (4108ms)
    ✓ should list checkpoints (458ms)
    ✓ should delete checkpoint (980ms)

  mavensmate clean-project-command
    ✓ should revert the project to server state based on package.xml (9636ms)
    ✓ should respect the user updating the package.xml file directly (7724ms)

  mavensmate compile-metadata
    ✓ should compile an apex class successfully via the tooling api (7289ms)
    ✓ should check for conflicts on the server (3506ms)
    ✓ should unsuccessfully attempt to compile an apex class via the tooling api (6463ms)
    ✓ should compile a meta.xml file via the metadata api (5058ms)
    ✓ should compile an object file via the metadata api (7258ms)

  mavensmate compile-project
    ✓ should compile the project based on package.xml (4038ms)

  mavensmate delete-metadata
    ✓ should create then delete metadata from server (8028ms)

  mavensmate deploy-to-server
    ✓ should require at least one deploy target
    ✓ should validate deploy to an org connection (9689ms)

  mavensmate edit-project
    ✓ should edit project contents (1993ms)
    ✓ should fail to update project creds because of invalid login (1623ms)
    ✓ should update project creds (1669ms)

  mavensmate execute-apex
    ✓ should execute anonymous apex (465ms)
    ✓ should attempt to execute invalid anonymous apex (444ms)

  mavensmate execute-soql
    ✓ should successfully execute soql query (474ms)
    ✓ should fail to execute soql query (439ms)

  mavensmate index-apex
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:179:15)
    at Object.fs.watchFile (fs.js:1285:8)
    at Client._monitorConfigFile (/Users/ralphcallaway/MavensMate/MavensMate/lib/mavensmate/client.js:300:6)
    at Client._initConfig (/Users/ralphcallaway/MavensMate/MavensMate/lib/mavensmate/client.js:277:10)
    at new exports.Client (/Users/ralphcallaway/MavensMate/MavensMate/lib/mavensmate/client.js:54:8)
    at Object.exports.createClient (/Users/ralphcallaway/MavensMate/MavensMate/lib/mavensmate/client.js:502:10)
    at Object.exports.createClient (/Users/ralphcallaway/MavensMate/MavensMate/test/test-helper.js:41:21)
    at Context.<anonymous> (/Users/ralphcallaway/MavensMate/MavensMate/test/integration/commands/index-apex.js:18:25)
    at callFnAsync (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/mocha/lib/runnable.js:306:8)
    at Hook.Runnable.run (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/mocha/lib/runnable.js:261:7)
    at next (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/mocha/lib/runner.js:297:10)
    at Immediate._onImmediate (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/mocha/lib/runner.js:319:5)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
(node) warning: possible EventEmitter memory leak detected. 11 sfdcclient-new-log listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at SalesforceClient.addListener (events.js:179:15)
    at /Users/ralphcallaway/MavensMate/MavensMate/lib/mavensmate/project.js:262:27
    at tryCatch1 (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/promise.js:733:18)
    at Promise._settlePromises (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/promise.js:845:14)
    at Async._consumeFunctionBuffer (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Users/ralphcallaway/MavensMate/MavensMate/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:355:11)
    ✓ should index project apex symbols (1154ms)
    ✓ should index apex symbols for a specific apex class (3530ms)

  mavensmate index-metadata
    ✓ should index metadata based on the project subscription (6306ms)
    ✓ should fail to index due to unknown type
    ✓ should index uncommon types (6364ms)
    ✓ should get metadata index from project

  mavensmate lightning
    ✓ should create a new lightning app (4173ms)
    ✓ should create a new lightning component (3905ms)
    ✓ should create a new lightning interface (3586ms)
    ✓ should create a lightning event (3547ms)

  mavensmate logging
    ✓ should start logging for all user ids listed in config/.debug (955ms)
    ✓ should stop logging for all user ids listed in config/.debug (961ms)

  mavensmate new-metadata
    ✓ should create new Apex Class on the server (3100ms)
    ✓ should create new Apex Trigger on the server (3288ms)

  mavensmate new-project
    ✓ should require username and password
    ✓ should prompt that project directory already exists (1474ms)
    ✓ should prompt because of bad salesforce creds (1730ms)
    1) should create project in specified workspace

  mavensmate open-metadata
    ✓ should return the Visualforce page preview url (3336ms)

  mavensmate org-connections
    ✓ should add a new org connection (1474ms)
    ✓ should get org connections
    ✓ should not add an org connection because of bad credentials (1495ms)
    ✓ should delete an org connection

  mavensmate refresh-metadata
    ✓ should refresh class directory from the server (5007ms)
    ✓ should refresh class file from the server (5117ms)
    ✓ should refresh a CustomObject from the server  (1967ms)
    2) should refresh project 

  mavensmate resource-bundle
    ✓ should create a resource bundle from a local static resource file
    ✓ should throw exception when trying to create resource bundle that already exists
    ✓ should deploy a resource bundle to the server (2116ms)

  mavensmate run-tests
    ✓ should run tests (13973ms)
    coverage
      ✓ should get coverage for a specific class (533ms)
      ✓ should get org-wide test coverage (476ms)

  mavensmate session
    ✓ should initiate new salesforce session (1641ms)
    ✓ should fail to initiate new salesforce session (1425ms)

  mavensmate update-subscription
    ✓ should update the project subscription

  mavensmate new-apex-script-cli

  error: unknown option `--recursive'
```

**Comment by ralphcallaway** [comment]
looks like the issue is that make test is looking for a TESTS2 env variable that is only set for CI scripts

unrelated mocha seems to have some bugs with --recursive that cause it to error out if a file path isn't specified (see http://bpinto.github.io/posts/running-mocha-tests-on-subdirectories/), tried things out with a new test mocha project and the bug doesn't occur, since TESTS2 is null you get this error

went ahead and updated the readme.md since this also occurs when running tests directly with mocha without specifying a directory (see cb0949adaf3b62122857eab79c04db1fbe0b1b7d)
