### ISSUE TITLE
refresh-metadata integration test fails when run locally

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#617]
test results
```
➜  MavensMate git:(test_ci_fix) mocha --recursive -g refresh-metadata ./test/


  mavensmate refresh-metadata
    ✓ should refresh class directory from the server (5254ms)
    ✓ should refresh class file from the server (5008ms)
    ✓ should refresh a CustomObject from the server  (2128ms)
    1) should refresh project 

  mavensmate refresh-metadata-cli
    ✓ should accept a metadata path
    ✓ should accept stdin


  5 passing (29s)
  1 failing

  1) mavensmate refresh-metadata should refresh project :

      AssertionError: expected false to equal true
      + expected - actual

      -false
      +true
      
      at test/integration/commands/refresh-metadata.js:147:113
      at tryCatch1 (node_modules/bluebird/js/main/util.js:45:21)
      at Promise._callHandler (node_modules/bluebird/js/main/promise.js:571:13)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:733:18)
      at Promise._settlePromises (node_modules/bluebird/js/main/promise.js:845:14)
      at Async._consumeFunctionBuffer (node_modules/bluebird/js/main/async.js:85:12)
      at Async.consumeFunctionBuffer (node_modules/bluebird/js/main/async.js:40:14)
```

**Comment by ralphcallaway** [comment]
assertion is looking for a custom object `CoolObject__c` to be in the refreshed project, but nothing is creating that object first

it's passing on circle since the org used their has that object
