### ISSUE TITLE
Unable to create new mm project

### ISSUE THREAD

**Issue by robertwalc** [joeferraro/MavensMate#621]
Hi,

Im using Sublime Text 3 on Windows 10 64bit when I try to create a new project I get following error:

Traceback (most recent call last): File "", line 12, in File "", line 9, in main File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 95, in execute File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request", line 133, in __printr File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\json", line 243, in dumps File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\json.encoder", line 207, in encode File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\json.encoder", line 270, in iterencode UnicodeDecodeError: 'utf8' codec can't decode byte 0xea in position 21: invalid continuation byte

What can be a reason for that? Does anyone know a workaround for this?

Best regards,

Robert Walc

**Comment by ralphcallaway** [comment]
@robertwalc can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by robertwalc** [comment]
1. I am running Windows 10 64 bit architecture
I have installed Sublime Text 3 Build 3083 with Package control
2. Using Package control I install latest version of MM: MavensMate for Sublime Text v6.0.0
3. Im neither behind a Firewall nor Proxy
4. Steps to reproduce: I try to create a new Project: MavensMate -> Project -> New Project
When the Page for Project details appears I provide: Project name, User name, Password with Security token and change type to Developer as I try to connect to my Developer org
Then the Message "Creating new MavensMate project" is being displayed, but noting was displayed - finally I got the message that I posted.

But what is funny - while trying to prepare those replication steps I have managed to create a project so I am closing the issue :)

**Comment by PiotrPotocki** [comment]
Hello All, 

I have the same issue like @robertwalc. I am running MM on Windows 10 64-bit (Sublime Text 3 Build 3103) machine.
The same steps to reproduce. The same error message during creation of new project. 
Do you know if there exists any workaround or fix?
