### ISSUE TITLE
[ERROR]: Could not extract and write stream to file system.

### ISSUE THREAD

**Issue by kkepa** [joeferraro/MavensMate#708]
* **MavensMate Version**: v 7.0.0

* **Editor**: Sublime Text 

* **Platform/Version**: Windows 10 64-bit

* **Proxy Details**: No

* **Salesforce Server**: i.e. cs 14

After update to v 7.0.0 I cannot refresh anything (any class, page, etc...) from the server. Regardless of file I want to refresh I get the "[ERROR]: Could not extract and write stream to file system."error. Deploying/saving changes works normally... Same when I go to edit project and try to refresh the metadata through the client app, see below:
![err maven](https://cloud.githubusercontent.com/assets/22152878/18442055/987acce6-790f-11e6-89d1-130a313e0b13.PNG)

**Comment by kkepa** [comment]
Below is the full log:

`Calling mavensmate adapter
OPERATION: refresh-metadata
{'body': {'paths': ['C:\\maven_workspace\\proj\\src\\classes\\Batch_Compute_Inventory_Scheduler.cls']}, 'context': <MavensMate.mavensmate.RefreshActiveFileCommand object at 0x000000C75E70BA90>}
http://localhost:56248/execute?command=refresh-metadata&async=1&pid=U2TPSPF74X98JTQBCLVQZN2LZHID159K
posting to MavensMate:
b'{"paths": ["C:\\\\maven_workspace\\\\proj\\\\src\\\\classes\\\\Batch_Compute_Inventory_Scheduler.cls"]}'
response from MavensMate
<http.client.HTTPResponse object at 0x000000C75E7AA8D0>
{'complete': True, 'operation': 'refresh-metadata', 'id': '7322d850-798a-11e6-91c7-ff11ff2934b0', 'stack': 'Error: Could not extract and write stream to file system.\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\util.js:427:35\n    at tryCatcher (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\util.js:26:23)\n    at Promise._settlePromiseFromHandler (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:503:31)\n    at Promise._settlePromiseAt (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:577:18)\n    at Promise._settlePromises (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:693:14)\n    at Async._drainQueue (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:123:16)\n    at Async._drainQueues (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:371:17)', 'error': 'Could not extract and write stream to file system.'}
Could not load json response from mavensmate
{'complete': True, 'operation': 'refresh-metadata', 'id': '7322d850-798a-11e6-91c7-ff11ff2934b0', 'stack': 'Error: Could not extract and write stream to file system.\n    at C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\mavensmate\\lib\\mavensmate\\util.js:427:35\n    at tryCatcher (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\util.js:26:23)\n    at Promise._settlePromiseFromHandler (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:503:31)\n    at Promise._settlePromiseAt (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:577:18)\n    at Promise._settlePromises (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\promise.js:693:14)\n    at Async._drainQueue (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:123:16)\n    at Async._drainQueues (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:133:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (C:\\Program Files\\MavensMate\\resources\\app\\node_modules\\bluebird\\js\\main\\async.js:15:14)\n    at processImmediate [as _immediateCallback] (timers.js:371:17)', 'error': 'Could not extract and write stream to file system.'}`

**Comment by kkepa** [comment]
And another deubug log, maybe a bit more clear:

Note: I did change the naming of component to "somecomponent" on purpose...

`2016-09-13T08:37:30.776Z - info: executeCommandForProject payload is: {"paths":["C:\\maven_workspace\\project\\src\\components\\somecomponent.component"]}
2016-09-13T08:37:30.776Z - debug: command class is: RefreshMetadataCommand
2016-09-13T08:37:30.776Z - debug: refreshing paths from server ...
2016-09-13T08:37:30.776Z - debug: initing package instance with subscription: 
2016-09-13T08:37:30.776Z - debug:  ApexComponent=[somecomponent]
2016-09-13T08:37:30.776Z - debug: _ensureCustomObjectSubscriptionIsValid
2016-09-13T08:37:30.776Z - debug: submitting retrieve request for pkg metadata
2016-09-13T08:37:30.776Z - debug:  ApexComponent=[somecomponent]
2016-09-13T08:37:30.776Z - debug: retrieving unpackaged: 
2016-09-13T08:37:30.776Z - debug:  ApexComponent=[somecomponent]
2016-09-13T08:37:30.791Z - debug: Processing request GET for URL: /status?id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:30.791Z - debug: query params id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:31.307Z - debug: Processing request GET for URL: /status?id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:31.307Z - debug: query params id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:31.824Z - debug: Processing request GET for URL: /status?id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:31.824Z - debug: query params id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:32.328Z - debug: Processing request GET for URL: /status?id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:32.328Z - debug: query params id=4f376980-798d-11e6-a2af-219343039004
2016-09-13T08:37:32.382Z - debug: writing stream
2016-09-13T08:37:32.397Z - debug: closed write stream, unzipping now
2016-09-13T08:37:32.413Z - debug: cscriptExe is:  cscript
2016-09-13T08:37:32.460Z - error: ERR unzipping:
2016-09-13T08:37:32.460Z - error:  0=67, 1=58, 2=92, 3=80, 4=114, 5=111, 6=103, 7=114, 8=97, 9=109, 10=32, 11=70, 12=105, 13=108, 14=101, 15=115, 16=92, 17=77, 18=97, 19=118, 20=101, 21=110, 22=115, 23=77, 24=97, 25=116, 26=101, 27=92, 28=114, 29=101, 30=115, 31=111, 32=117, 33=114, 34=99, 35=101, 36=115, 37=92, 38=97, 39=112, 40=112, 41=92, 42=110, 43=111, 44=100, 45=101, 46=95, 47=109, 48=111, 49=100, 50=117, 51=108, 52=101, 53=115, 54=92, 55=109, 56=97, 57=118, 58=101, 59=110, 60=115, 61=109, 62=97, 63=116, 64=101, 65=92, 66=98, 67=105, 68=110, 69=92, 70=117, 71=110, 72=122, 73=105, 74=112, 75=46, 76=118, 77=98, 78=115, 79=40, 80=50, 81=53, 82=44, 83=32, 84=53, 85=41, 86=32, 87=40, 88=110, 89=117, 90=108, 91=108, 92=41, 93=58, 94=32, 95=85, 96=110, 97=115, 98=112, 99=101, 100=99, 101=105, 102=102, 103=105, 104=101, 105=100, 106=32, 107=101, 108=114, 109=114, 110=111, 111=114, 112=32, 113=13, 114=10, 115=13, 116=10, length=117, parent=undefined
2016-09-13T08:37:32.460Z - error: error retrieving and writing to disk
2016-09-13T08:37:32.460Z - error: Could not extract and write stream to file system.
2016-09-13T08:37:32.460Z - debug: Could not refresh metadata: Could not extract and write stream to file system.
2016-09-13T08:37:32.460Z - debug: Could not complete refresh request: Could not extract and write stream to file system.`

Any ideas what could cause it ?
For now, I've just removed Mavens plugin and manually replaced it with version 6.0.3 which is working fine....

**Comment by lynnellemmanuel** [comment]
The same problem here. Windows 8.1 64 bit. MavensMate-App v0.0.10

![mavensmate-bug](https://cloud.githubusercontent.com/assets/7625546/18573679/51718af6-7bf8-11e6-84ce-5ffe107ff5e0.PNG)

**Comment by joeferraro** [comment]
This has been resolved in 0.0.11-beta.4
https://github.com/joeferraro/MavensMate-Desktop/releases
