### ISSUE TITLE
Timing out often

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate#761]
v0.0.11-beta.6

Sublime

7

OS X 10.11.6

37

While compiling I have been getting Result: [ERROR]: connect ETIMEDOUT 136.146.210.114:443 randomly. Saving again and still see it... sometimes immediately. Wait a few seconds and it saves again.

Log from one of these

2016-09-23T14:18:40.042Z - debug:   compiling paths: 
2016-09-23T14:18:40.042Z - debug:    0=/Users/kyle/workspace/MedInfo-Product/src/classes/AccountSearchCtrlTest.cls
2016-09-23T14:18:40.046Z - debug:   compiling via metadata api
2016-09-23T14:18:40.046Z - debug:    ApexClass=[AccountSearchCtrlTest]
2016-09-23T14:18:40.047Z - debug:   checking for conflicts
2016-09-23T14:18:40.077Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:40.078Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:40.590Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:40.591Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:41.098Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:41.099Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:41.605Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:41.606Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:42.110Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:42.110Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:42.618Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:42.618Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:43.126Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:43.126Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:43.634Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:43.635Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:44.141Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:44.141Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:44.650Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:44.650Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:45.156Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:45.156Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:45.663Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:45.663Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:46.171Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:46.171Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:46.678Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:46.678Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:47.182Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:47.182Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:47.691Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:47.691Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:47.966Z - error:   SOQL for server copy failed connect ETIMEDOUT 136.146.210.114:443
2016-09-23T14:18:47.969Z - error:   error checking conflicts Error: connect ETIMEDOUT 136.146.210.114:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
2016-09-23T14:18:47.970Z - info:    handling command result
2016-09-23T14:18:47.970Z - error:    Error: connect ETIMEDOUT 136.146.210.114:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
2016-09-23T14:18:47.970Z - debug:   finishing requestId: 9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:47.970Z - error:    Error: connect ETIMEDOUT 136.146.210.114:443
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
2016-09-23T14:18:48.200Z - debug:   Processing request GET for URL: /status?id=9ffc6830-8198-11e6-95fe-b921f6723783
2016-09-23T14:18:48.200Z - debug:   query params id=9ffc6830-8198-11e6-95fe-b921f6723783

**Comment by joeferraro** [comment]
It's probably that this is a Salesforce server issue, I don't see anything in the logs that suggests otherwise. Closing until it can be pinned to a local issue.
