### ISSUE TITLE
Failed to load the MavensMate-Atom package At Cannot find module 'browser-window'

### ISSUE THREAD

**Issue by dantuck** [joeferraro/MavensMate#777]
[Enter steps to reproduce below:]

1. start atom

**Atom Version**: 1.10.2
**Electron Version**: 1.4.1
**System**: linux 4.7.5-1-ARCH
**Thrown From**: [MavensMate-Atom](https://github.com/joeferraro/MavensMate-Atom) package, v1.0.9

### Stack Trace

Failed to load the MavensMate-Atom package

```
At Cannot find module 'browser-window'
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

Error: Cannot find module 'browser-window'
Error: Cannot find module 'browser-window'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at EventEmitter.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/rpc-server.js:232:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/usr/lib/electron/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/usr/lib/electron/resources/electron.asar/renderer/api/remote.js:217:13)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/salesforce-view.coffee:5:24)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/salesforce-view.coffee:1:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/util.coffee:8:21)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/util.coffee:1:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/project-list-view.coffee:4:21)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/project-list-view.coffee:1:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:9:25)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:1:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/main.coffee:1:26)
    at Object.<anonymous> (/home/daniel/.atom/packages/MavensMate-Atom/lib/main.coffee:1:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Package.module.exports.Package.requireMainModule (/usr/lib/atom/src/package.js:718:27)
    at /usr/lib/atom/src/package.js:117:28
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/lib/atom/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/lib/atom/src/package-manager.js:449:14)
    at /usr/lib/atom/src/package-manager.js:394:19
    at Config.module.exports.Config.transact (/usr/lib/atom/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/lib/atom/src/package-manager.js:389:19)
    at /usr/lib/atom/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
autocomplete-go, v1.2.0 (inactive)
build, v0.65.0 (inactive)
busy, v0.7.0 (inactive)
file-icons, v1.7.19 (inactive)
git-plus, v5.17.1 (inactive)
git-time-machine, v1.5.3 (inactive)
go-config, v1.2.4 (inactive)
go-get, v2.0.0 (inactive)
linter, v1.11.16 (inactive)
markdown-writer, v2.6.1 (inactive)
MavensMate-Atom, v1.0.9 (inactive)
minimap, v4.25.0 (inactive)
pigments, v0.35.2 (inactive)
script, v3.10.1 (inactive)
terminal-plus, v0.14.5 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by steals** [comment]
go to ~/.atom/packages/Mavensmate-Atom and run npm install

**Comment by dantuck** [comment]
@steals I gave that a try but the issue persisted. Just to ensure I had no conflicting packages I removed the atom package `sudo pacman -R atom` and then removed the configs `rm -Rf ~/.atom`. Then reinstalled `sudo pacman -S atom` and opened atom and found no errors. Then installed only the Mavensmate-Atom package `apm install Mavensmate-Atom`. Opened atom once again and I get the same error. Also just an extra not I am running the Mavensmate-App v0.0.10 during this whole process.

Thank you for your help.
