### ISSUE TITLE
"result.resolve is not a function" error with Sublime text

### ISSUE THREAD

**Issue by tuskiomi** [joeferraro/MavensMate#788]
- **MavensMate Desktop Version**: 0.11-b6

- **Editor**: sublime

- **MavensMate Plugin Version**:7

- **Platform/Version**: Windows 7 64 bit

- **Proxy Details**: N/A

- **Salesforce API Version**: 37

- **Salesforce Server**: N/A

I've downloaded the plugin and desktop app, but now whenever I create a new file by right clicking the folder -> new file, and try to save it, I get the following error:

Operation: Handling requested operation...
Timestamp: Wed, 05 Oct 2016 11:36:43
   Result: [ERROR]: result.resolve is not a function

I've went and made sure all of my paths are correct, and I have found that they are.

#I'm closing this ticket as I've found a solution. here it is:

In the sublime text Mavens-Mate settings make sure that both your path to mavensmate AND your path to sublime text is correct. Then under Mavensmate Global settings (the gear), go down to **The full path of your Sublime Text executable (Sublime Text users only).** and change the path to correct location. Make sure with windows, you're using "\\" instead of a "\" in your path.

**Comment by Autobat** [comment]
Also experiencing the problem with a fresh install:

* Sublime Text 3
* "osx": "/Applications/Sublime Text 3.app/Contents/SharedSupport/bin/subl"
* Removed and reinstalled MavensMate
* Downloaded MavensMate-Desktop-0.0.11-beta.6-mac
* SFDC API 36

**Comment by iprscsl** [comment]
I am facing the same issue as well. From Sublime Text 3, going to 'Mavensmate -> Project -> clean project', this works and updates the files with the files from Salesforce org.
But when we modify an apex class file and save it, I get this error "Result: [ERROR]: result.resolve is not a function"

**Comment by sposey** [comment]
Same as Autobat, but getting this when using the MavensMate Deploy To Server functionality:

```
[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: deploy
[MAVENSMATE]: {'body': {'args': {'ui': True}}}
[MAVENSMATE]: http://localhost:56248/execute?command=deploy&async=1&pid=405c77b0-a21a-11e6-8213-bf0583a4c81b
[MAVENSMATE]: posting to MavensMate:
[MAVENSMATE]: b'{"args": {"ui": true}}'
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x108356150>
[MAVENSMATE]: {'stack': 'TypeError: result.resolve is not a function\n    at _handleCommandResult (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/commands/index.js:55:16)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/commands/index.js:143:11\n    at Object.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/commands/index.js:87:14)\n    at _execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/routes/execute.js:33:33)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:235:24\n    at Function.proto.process_params (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:313:12)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:229:12\n    at Function.match_layer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:296:3)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:190:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:215:18\n    at Function.match_layer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:296:3)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:190:10)', 'id': 'f1f08eb0-a226-11e6-8213-bf0583a4c81b', 'complete': True, 'error': 'result.resolve is not a function'}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'stack': 'TypeError: result.resolve is not a function\n    at _handleCommandResult (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/commands/index.js:55:16)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/commands/index.js:143:11\n    at Object.execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/commands/index.js:87:14)\n    at _execute (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/routes/execute.js:33:33)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:100:13)\n    at Route.dispatch (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:81:3)\n    at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:235:24\n    at Function.proto.process_params (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:313:12)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:229:12\n    at Function.match_layer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:296:3)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:190:10)\n    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:215:18\n    at Function.match_layer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:296:3)\n    at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:190:10)', 'id': 'f1f08eb0-a226-11e6-8213-bf0583a4c81b', 'complete': True, 'error': 'result.resolve is not a function'}
```

**Comment by seyitbek** [comment]
I am getting this exact same problem! Could someone please suggest a solution? Otherwise I cannot advance in Apex Academy! :((

**Comment by seyitbek** [comment]
@joeferraro could you please see if you can resolve this? Your advice is highly appreciated.

**Comment by tuskiomi** [comment]
Solution found, see OP.

**Comment by seyitbek** [comment]
what does it mean see OP?

**Comment by seyitbek** [comment]
@tuskiomi what does it mean see OP?

**Comment by tuskiomi** [comment]
Scroll up to the top and check the Original Post.




Sent from my Samsung Galaxy Tab®|PRO


-------- Original message --------
From: Seyitbek Usmanov
Date:21/11/2016 10:06 PM (GMT-06:00)
To: joeferraro/MavensMate
Cc: tuskiomi ,Mention
Subject: Re: [joeferraro/MavensMate] "result.resolve is not a function" error with Sublime text (#788)


@tuskiomi<https://github.com/tuskiomi> what does it mean see OP?

-
