### ISSUE TITLE
connect ETIMEDOUT Error

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate#797]
* **MavensMate Desktop Version**: 0.0.9

* **Editor**: Sublime

* **MavensMate Plugin Version**: 7.0.2

* **Platform/Version**: Windows 10 64-bit

* **Salesforce API Version**: 34.0

* **Salesforce Server**: na37

Getting the above error every couple of saves or so returning:

```
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x000001BFCD612780>
[MAVENSMATE]: {'id': '91375870-91f4-11e6-9fdc-d707d73c5fd3', 'operation': 'compile-metadata', 'error': 'connect ETIMEDOUT 136.147.56.228:443', 'complete': True, 'stack': 'Error: connect ETIMEDOUT 136.147.56.228:443\n    at Object.exports._errnoException (util.js:814:11)\n    at exports._exceptionWithHostPort (util.js:837:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)'}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'id': '91375870-91f4-11e6-9fdc-d707d73c5fd3', 'operation': 'compile-metadata', 'error': 'connect ETIMEDOUT 136.147.56.228:443', 'complete': True, 'stack': 'Error: connect ETIMEDOUT 136.147.56.228:443\n    at Object.exports._errnoException (util.js:814:11)\n    at exports._exceptionWithHostPort (util.js:837:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)'}
```

```
Operation: Compiling Selected Metadata
Timestamp: Fri, 14 Oct 2016 10:57:07
Result: [ERROR]: connect ETIMEDOUT 136.147.56.228:443
```

If it give it one or two more tries, it tends to work. Looks like a network issue of some sort but do you happen to know any reason behind it?

**Comment by LKozakewycz** [comment]
This never stopped happening. This happens every day and so much so that I have to give up developing on regular basis.

**Comment by joeferraro** [comment]
Are you running behind a firewall/proxy?

**Comment by jvg123** [comment]
Similar thing happens for me. Sometimes compiles go through really fast, more often they get stuck with endless spinner showing.

I also saw this error when doing a "Run APEX Tests For This Class": the timeout occurred after about 25 secs, whereas mm_timeout for the project is set to 600.

Relevant log snippets  below.

I am not behind a firewall or proxy.

===============
2017-01-11T00:29:20.655Z - debug: Processing request POST for URL: /execute?command=run-tests&async=1&pid=JORYIBHFW7EU8G1CW5V8WAK7LN91EAUC
2017-01-11T00:29:20.655Z - debug: post body skipCoverage=true, tests=[TestAssignmentHelper]
2017-01-11T00:29:20.657Z - info: 

==================> executing command: run-tests

2017-01-11T00:29:20.657Z - info: executeCommandForProject payload is: {"skipCoverage":true,"tests":["TestAssignmentHelper"]}
2017-01-11T00:29:20.657Z - debug: command class is: RunTestsCommand
2017-01-11T00:29:20.659Z - debug: adding test to job TestAssignmentHelper.cls
2017-01-11T00:29:20.659Z - debug: running the following tests: 
2017-01-11T00:29:20.659Z - debug:  0=01pd0000002vvugAAA
2017-01-11T00:29:20.660Z - debug: submitting tests to be run via runTestsAsynchronous: classids=01pd0000002vvugAAA
2017-01-11T00:29:20.664Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:20.664Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:21.171Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:21.171Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:21.675Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:21.675Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:22.184Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:22.184Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:22.694Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:22.694Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:23.202Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:23.202Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:23.709Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:23.709Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:24.064Z - info: result from runTestsAsynchronous POST 707d000005VxqoF
2017-01-11T00:29:24.214Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:24.214Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:24.720Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:24.720Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:25.225Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:25.225Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:25.442Z - debug: test status: 
2017-01-11T00:29:25.442Z - debug:  size=0, totalSize=0, done=true, queryLocator=null, entityTypeName=null, records=[]
2017-01-11T00:29:25.735Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:25.735Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:26.245Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:26.245Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:26.754Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:26.754Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:27.259Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:27.259Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:27.767Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:27.768Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:28.276Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:28.276Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:28.784Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:28.784Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:29.292Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:29.292Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:29.798Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:29.799Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:30.305Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:30.305Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:30.811Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:30.811Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:31.318Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:31.318Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:31.822Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:31.822Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:32.333Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:32.333Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:32.839Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:32.839Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:33.346Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:33.346Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:33.853Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:33.854Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:34.362Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:34.362Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:34.867Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:34.867Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:35.377Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:35.377Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:35.881Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:35.881Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:36.388Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:36.388Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:36.892Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:36.892Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:37.395Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:37.395Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:37.903Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:37.903Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:38.407Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:38.407Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:38.913Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:38.913Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:39.422Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:39.423Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:39.928Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:39.928Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:40.435Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:40.435Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:40.940Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:40.941Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:41.449Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:41.450Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:41.959Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:41.959Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:42.468Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:42.469Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:42.975Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:42.975Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:43.486Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:43.487Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:43.991Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:43.991Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:44.496Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:44.496Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:45.001Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:45.001Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:45.565Z - debug: Processing request GET for URL: /status?id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:45.565Z - debug: query params id=fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:45.932Z - error: Could not run tests
2017-01-11T00:29:45.932Z - error:  Error: Retrieving test results failed: connect ETIMEDOUT 96.43.148.100:443
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:616:20
    at tryCatch1 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
    at Promise._settlePromises (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
    at Async._consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
2017-01-11T00:29:45.934Z - info: handling command result: 
2017-01-11T00:29:45.934Z - error:  Error: Retrieving test results failed: connect ETIMEDOUT 96.43.148.100:443
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:616:20
    at tryCatch1 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
    at Promise._settlePromises (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
    at Async._consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)
2017-01-11T00:29:45.935Z - debug: finishing jobid: fe83c900-d794-11e6-b46e-810726bde1ba
2017-01-11T00:29:45.935Z - error:  Error: Retrieving test results failed: connect ETIMEDOUT 96.43.148.100:443
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/lib/mavensmate/sfdc-client.js:616:20
    at tryCatch1 (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:733:18)
    at Promise._settlePromises (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:845:14)
    at Async._consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/node_modules/bluebird/js/main/async.js:40:14)
    at doNTCallback0 (node.js:416:9)
    at process._tickCallback (node.js:345:13)

**Comment by LKozakewycz** [comment]
This is in the end was the result of our router supplied by Virgin Media. The issue occurs for many people where it drops packets in an attempt to protect against IP flooding. Despite some routers having a setting to switch this off, this has been a known fault with Virgin for a while.

Luckily, we also run a BT router in our office, so we decided to route all our Salesforce traffic through the BT router instead. This has since fixed the issue for us.

**Comment by jvg123** [comment]
Hmm, that is not something I would have thought to check.... I will try from a different location.

Any idea why would this happen with MavensMate specifically? I have not noticed similar issues with with other tools. Specifically the Force.com IDE seems to work OK, whereas MavensMate is practically unusable

**Comment by LKozakewycz** [comment]
My guess is that all IDE's work slightly differently. Illuminated Cloud has been working for some developers but still slower than normal whereas Mavensmate just full on conks out. Since programming our switch to send Salesforce traffic through a different, more reliable router and ISP, it has made a huge difference.

I'm not saying this is your issue though. This is just my experience and can differ for everyone. Our last resort was to mess with our networking as Salesforce, the IDE and the PC denied all responsibility at the time.

**Comment by jvg123** [comment]
I still experience this periodically from different locations. 20% of the time it works fine, 40% of the time it works but super slow, 40% of the time I get the timeout.

I've tried both with and without mm_compile_with_tooling_api -- issues happens with both, although tooling seems more reliable.

Timeout seems to occur after ~40 secs, although my timeout is set to 2000

**Comment by praveenmakam2012** [comment]
any update on this thread? I am not able to create a project. When I click on 'create project' in the desktop app, it tries to load but fails with 'connet E timedout 101.53.163.130:443'error. I changed the timeout setting to 600. It never used to happen.

How do I check if I am behing a firewall/proxy network? Thanks

**Comment by mikearthur7b0** [comment]
> 
> 
> any update on this thread? I am not able to create a project. When I click on 'create project' in the desktop app, it tries to load but fails with 'connet E timedout 101.53.163.130:443'error. I changed the timeout setting to 600. It never used to happen.
> 
> How do I check if I am behind a firewall/proxy network? Thanks

see reply above from LKozakewycz - mine has been working fine for ever, until tonight I was getting timeout error.  Rebooted router and boom - I'm sucking metadata again :-)
