### ISSUE TITLE
Atom: typing single quote for attribute value in VF page causes exception.

### ISSUE THREAD

**Issue by jclark-dot-org** [joeferraro/MavensMate#799]
* **MavensMate Desktop Version**: MavensMate-app v0.0.10

* **Editor**: Atom

* **MavensMate Plugin Version**:  1.0.9

* **Platform/Version**: OS X 10.10.5

* **Proxy Details**: N/A

* **Salesforce API Version**: 36.0

* **Salesforce Server**:  editor issue - Occurs on all servers

**Reproduction steps**:
Edit a Visualforce page.  Try to add an attribute value to an apex or html tag using a single quote instead of a double quote.  For example:

    <apex:outputLabel value='Search' />

or 

    <div class='test'>

In each case, when you type the first single quote, an exception is thrown:

> Uncaught TypeError: Cannot read property 'attributes' of undefined
/Users/jclark/.atom/packages/mavensmate-atom/lib/autocomplete/providers.coffee:221
Hide Stack Trace
TypeError: Cannot read property 'attributes' of undefined
   at Object.VisualforceTagProvider.getAttributeValues (/Users/jclark/.atom/packages/mavensmate-atom/lib/autocomplete/providers.coffee:221:29)
   at Object.VisualforceTagProvider.getAttributeValueCompletions (/Users/jclark/.atom/packages/mavensmate-atom/lib/autocomplete/providers.coffee:179:15)
   at Object.VisualforceTagProvider.getSuggestions (/Users/jclark/.atom/packages/mavensmate-atom/lib/autocomplete/providers.coffee:67:10)
   at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:325:56
   at Array.forEach (native)
   at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:304:17)
   at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
   at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:291:19)
   at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

This issue was originally reported [here][1].

[1]: https://github.com/joeferraro/MavensMate-Atom/issues/294

**Comment by jclark-dot-org** [comment]
Only because years of writing Apex has trained me to avoid the doublequote.  I don't have a preference, and tend to use doublequotes in VF mostly due to this issue.  It's just jarring when muscle memory takes over and I get an exception pop-up in Atom.

**Comment by joeferraro** [comment]
@jclark-dot-org no worries, wanted to make sure I wasn't overlooking something obvious.

**Comment by adamdaw** [comment]
thanks all. I'm on it.
