### ISSUE TITLE
Run Apex Unit Tests

### ISSUE THREAD

**Issue by bk-dev** [joeferraro/MavensMate#805]
- **MavensMate Desktop Version**: 0.0.11-beta.6

- **Editor**: Sublime

- **MavensMate Plugin Version**: 7.0.2

- **Platform/Version**: OS X 10.10.3

- **Proxy Details**: N/A

- **Salesforce API Version**: 38.0

- **Salesforce Server**: cs13

In the MavensMate Desktop, I choose Run Apex Unit Tests and get the following screen:

```
Error: EISDIR: illegal operation on a directory, read
   at Error (native)
   at Object.fs.readSync (original-fs.js:731:19)
   at Object.fs.readSync (/Applications/MavensMate.app/Contents/Resources/app/node_modules/fs-extra-promise/node_modules/graceful-fs/polyfills.js:245:23)
   at tryReadSync (original-fs.js:486:20)
   at Object.fs.readFileSync (original-fs.js:534:19)
   at Object.fs.readFileSync (ELECTRON_ASAR.js:500:29)
   at Object.exports.getFileBody (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/util.js:299:21)
   at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/routes/test.js:72:27
   at Array.forEach (native)
   at _getTestClasses (/Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/routes/test.js:69:31)
   at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/routes/test.js:20:21
   at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)
   at next (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:82:5)
   at /Applications/MavensMate.app/Contents/Resources/app/node_modules/express/lib/router/index.js:235:24
```

**Comment by bk-dev** [comment]
Yea, I did. Not sure what to do at this point. I'm using the dev console for running tests at the moment.

**Comment by joeferraro** [comment]
perhaps related https://github.com/palantir/tslint/issues/1381

**Comment by joeferraro** [comment]
@bk-dev do you have Apex classes in your project?

**Comment by bk-dev** [comment]
Yes, I do. I noticed the referenced issue while troubleshooting, but I didn't know how it could apply to my situation.

**Comment by ChuckJonas** [comment]
that's typically an error you seen when trying to run Read on a directory instead of a file... Weird part is the call is `fs.readdirSync`...

**Comment by ChuckJonas** [comment]
@bk-dev, do you by chance have any Directories in your 'src/classes' folder?

**Comment by bk-dev** [comment]
@ChuckJonas, that was it. I had a hidden .vscode folder in there from trying to setup vs code for use with mavensmate. I deleted the .vscode folder and it works now.
