### ISSUE TITLE
Saving twice throws error

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate#82]
If I save a file and then try to save again before the save completes an error gets thrown.  tooling api is on. ST3. MM 3.0.4

==============================================
Compiling: OrdersPlacementMVN.page
Timestamp: Thu, 05 Sep 2013 12:32:36
Result:[      = ]
 
==============================================
Compiling: OrdersPlacementMVN.page
Timestamp: Thu, 05 Sep 2013 12:32:37
Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please report this issue at https://github.com/joeferraro/MavensMate-SublimeText
[RESPONSE FROM MAVENSMATE]: Traceback (most recent call last):

  File "<string>", line 301, in <module>

  File "<string>", line 53, in main

  File "<string>", line 104, in compile_selected_metadata

  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 340, in compile_selected_metadata

  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_client", line 474, in compile_with_tooling_api

TypeError: list indices must be integers, not str

[RESPONSE FROM MAVENSMATE]: Traceback (most recent call last):

  File "<string>", line 301, in <module>

  File "<string>", line 53, in main

  File "<string>", line 104, in compile_selected_metadata

  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_project", line 340, in compile_selected_metadata

  File "/Users/josephferraro/Development/Python/mavensmate/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.mm_client", line 474, in compile_with_tooling_api

TypeError: list indices must be integers, not str

**Comment by joeferraro** [comment]
this has been resolved in the upcoming release
