### ISSUE TITLE
MavensMate in Atom appears to be hanging, but it is actually saving

### ISSUE THREAD

**Issue by banderson5144** [joeferraro/MavensMate#846]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: Atom

* **MavensMate Plugin Version**: 1.0.9

* **Platform/Version**: Windows 7 64-Bit

* **Proxy Details**:

* **Salesforce API Version**: 36.0

* **Salesforce Server**: na34

Trying to save any type of file just shows the status bar at the bottom hanging
![image](https://cloud.githubusercontent.com/assets/2395774/20313580/5a338ef8-ab25-11e6-8a8d-545c61f15649.png)

**Comment by banderson5144** [comment]
Here is the logs
[mm_log.zip](https://github.com/joeferraro/MavensMate/files/593405/mm_log.zip)

**Comment by banderson5144** [comment]
Seems to be related to this file

https://github.com/joeferraro/MavensMate-Atom/blob/master/lib/panel/parsers.coffee

index.js:15 Unhandled promise rejection Promise_bitField: 136839168_fulfillmentHandler0: undefined_progressHandler0: undefined_promise0: undefined_receiver0: undefined_rejectionHandler0: undefined_settledValue: TypeError: Cannot read property 'result' of undefined
    at MavensMate.module.exports.MavensMate.adapterResponseHandler (file:///C:/Users/BryanSSD/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:259:36)
    at file:///C:/Users/BryanSSD/.atom/packages/MavensMate-Atom/lib/mavensmate.coffee:309:20
    at tryCatcher (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\promise.js:510:31)
    at Promise._settlePromiseAt (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)message: "Cannot read property 'result' of undefined"rawStack: Array[10]stack: (...)get stack: stack()set stack: stack()__proto__: Error__proto__: Object with error: TypeError: Cannot read property 'result' of undefined(…)(anonymous function) @ index.js:15emitTwo @ events.js:106emit @ events.js:191customEventWorks @ C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\captured_trace.js:420CapturedTrace.fireRejectionEvent @ C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\captured_trace.js:229Promise._notifyUnhandledRejection @ C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\debuggability.js:40Async._drainQueue @ C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\async.js:128Async._drainQueues @ C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\async.js:135Async.drainQueues @ C:\Users\BryanSSD\.atom\packages\MavensMate-Atom\node_modules\bluebird\js\main\async.js:15_tickCallback @ internal/process/next_tick.js:103

**Comment by banderson5144** [comment]
Ok I have narrowed it down @joeferraro it is the constructor of CommandParser in https://github.com/joeferraro/MavensMate-Atom/blob/master/lib/panel/parsers.coffee

@obj is null. Was there update to Atom that caused CoffeeScript to break

**Comment by ljsfdcdev** [comment]
+1 .. Not receiving any Success or Fail to compile messages, but the code is being compiled.

**Comment by joeferraro** [comment]
can someone confirm this PR resolves the issue? https://github.com/joeferraro/MavensMate-Atom/pull/340

**Comment by the1mattkaufman** [comment]
I just edited parsers.coffee and it did fix the issue running on Mac

**Comment by ordnajela** [comment]
It solved the issue running on Debian 8
