### ISSUE TITLE
MavensMate desktop closes after click to open

### ISSUE THREAD

**Issue by joralbert** [joeferraro/MavensMate#872]
Used the v0.0.10 installer

Sublime Text 3

Windows 7 x64, French/English

Yes, firewall

Hey Joe, thanks for your dev skills. My issue, after download and install mavensmate desktop, double click to open it. The MavensMate window opens and then it closes. **_Sometimes_**, it shows two error messages:

1.Unknown software exception (0x40000015)..
or
2. Uncaught exception Error: listen EADDRINUSE :::56248
at Object.exports._errnoException (util.js:814:11)
at exports._exceptionWithHostPort (util.js:837:20)
at Server._listen2 (net.js:1214:14)
at listen (net.js:1250:10)
at Server.listen (net.js:1340:5)
at UIServer.startServer (C:\Program Files\MavensMate\resources\app\node_modules)....

And I can't get it running.

**Comment by joralbert** [comment]
![image](https://cloud.githubusercontent.com/assets/7873843/21356145/8cdfaa82-c69e-11e6-8ece-ef64e1b234de.png)

**Comment by joralbert** [comment]
Found in task manager that the process MavensMate is running, but I don't have any MM desktop window to work with. Also, when I hit the MavensMate -> Show MM desktop from Sublime it shows: 

Result: [ERROR]: Request to the local MavensMate server failed, please ensure MavensMate Desktop is installed and running. For more information, please visit https://github.com/joeferraro/MavensMate/tree/master/docs
