### ISSUE TITLE
Mavensmate installtion on Atom fails

### ISSUE THREAD

**Issue by arohitu** [joeferraro/MavensMate#907]
* **MavensMate Desktop Version**: 0.0.11-beta 7
* **Editor**: Atom
* **MavensMate Plugin Version**:1.0.10
* **Platform/Version**: Windows 7 64 bit 
* **Proxy Details**: No
 When I try to install Ant it fails showing the below message. 
Installing “MavensMate-Atom@1.0.10” failed.Hide output…

npm WARN deprecated node-uuid@1.4.1: use uuid module instead
npm ERR! git clone C:\Users\rohitr.radhakrishnan\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: Cloning into 'C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! git clone C:\Users\rohitr.radhakrishnan\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\rohitr.radhakrishnan\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: fatal: unable to fork
npm ERR! git clone C:\Users\rohitr.radhakrishnan\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96: 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\rohitr.radhakrishnan\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\rohitr.radhakrishnan\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\rohitr.radhakrishnan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\rohitr.radhakrishnan\\.atom\\.apmrc" "install" "C:\\Users\\ROHITR~1.RAD\\AppData\\Local\\Temp\\d-11712-7116-1420tjg\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\rohitr.radhakrishnan\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96
npm ERR! Cloning into 'C:\Users\ROHITR~1.RAD\AppData\Local\Temp\npm-6784-5857c65e\git-cache-85c9de8c\e81b4b808359e2def9eeeabfdee69c2989e1fe96'...
npm ERR! error: cannot spawn sh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ROHITR~1.RAD\AppData\Local\Temp\apm-install-dir-11712-7116-139dr93\npm-debug.log

The debug.log file doesn't exist too.

Please help.

**Comment by kidtsunami** [comment]
Can you share a screenshot of what you're doing that causes this error?

**Comment by arohitu** [comment]
I click on install button on Mavensmate-Atom from the Atom > Install Package Screen. Then after few seconds I ran into this issue. I've Git, npm, apm all setup on my system.. Attaching screenshots.
![atom_mavensmate_installation_error](https://cloud.githubusercontent.com/assets/8843559/22579455/59c6be4e-e9f6-11e6-99d4-c03033dac37c.png)
![environmental variables](https://cloud.githubusercontent.com/assets/8843559/22579456/59c8ecb4-e9f6-11e6-80b0-77759da6bd7e.png)

**Comment by kidtsunami** [comment]
@arohitu Are you able to install other packages in Atom?

**Comment by arohitu** [comment]
Yes... I'm able to do that.

**Comment by steals** [comment]
Can you manually clone Mavensmate plugin (https://github.com/joeferraro/MavensMate-Atom.git) to your atom packages directory? (I think it's C:\Users\rohitr.radhakrishnan\.atom\packages)
And follow these steps:
1. git clone the package repo into ~/.atom/packages
2. cd into the package directory
3. type npm install
4. restart atom

**Comment by arohitu** [comment]
Hi. .Thanks for the update. Meanwhile I installed git from https://git-for-windows.github.io/
Then restarted the machine. Afterwards I could install Mavenmate. 
Really thanks for taking time looking into my issue.

**Comment by flinacio** [comment]
Hi, I'm having a similar problem and I could not even install as @steals mentioned. Here is my environment:
![image](https://cloud.githubusercontent.com/assets/16756774/24723160/c092574a-1a1c-11e7-9df1-fa6e1475c884.png)

And the error itself.

npm WARN deprecated node-uuid@1.4.1: Use uuid module instead
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:477:12)
npm WARN addRemoteGit  git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 resetting remote C:\Users\flinacio\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\flinacio\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\flinacio\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: Cloning into bare repository 'C:\Users\flinacio\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! git clone --template=C:\Users\flinacio\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\flinacio\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: fatal: unable to access 'https://github.com/Benvie/harmony-collections.git/': Received HTTP code 407 from proxy after CONNECT
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\flinacio\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\flinacio\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\flinacio\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\flinacio\\.atom\\.apmrc" "install" "C:\\Users\\flinacio\\AppData\\Local\\Temp\\d-11735-160-62avxs\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--msvs_version=2013"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\flinacio\.atom\.apm\_git-remotes\_templates --mirror https://github.com/Benvie/harmony-collections.git C:\Users\flinacio\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! Cloning into bare repository 'C:\Users\flinacio\.atom\.apm\_git-remotes\git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9'...
npm ERR! fatal: unable to access 'https://github.com/Benvie/harmony-collections.git/': Received HTTP code 407 from proxy after CONNECT
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\flinacio\AppData\Local\Temp\apm-install-dir-11735-160-hao24m\npm-debug.log

**Comment by steals** [comment]
@flinacio please check the solution here https://github.com/joeferraro/MavensMate/issues/890#issuecomment-319784406
