### ISSUE TITLE
Not able to create a new project in MavensMate Desktop

### ISSUE THREAD

**Issue by mKirti** [joeferraro/MavensMate#928]
* **MavensMate Desktop Version**: v0.0.10

* **Editor**: Not configured yet.

* **MavensMate Plugin Version**: Not configured yet.

* **Platform/Version**: Windows 7 32-bit

* **Proxy Details**: Windows firewall and Client proxy settings

* **Salesforce API Version**: 39.0

* **Salesforce Server**: ap2

I am getting the below error when i am trying to create a new project:

getaddrinfo ENOTFOUND login.salesforce.com login.salesforce.com:443

Please let me know the issue.

Thanks,
Kirti

**Comment by kidtsunami** [comment]
@mKirti do you have any firewall or proxy details? It looks like login.salesforce.com was not found, so either:

1. Your DNS settings have issues
2. salesforce.com was experiencing an outage
3. You have a proxy or firewall blocking those requests

**Comment by mKirti** [comment]
Hi David,

Thanks for your quick response.
Salesforce.com wasn’t experiencing a downtime as we were able to access our accounts successfully.

Can you let me know how do I check if it is a DNS or proxy or firewall issue?

Thanks,
Kirti

**Comment by mKirti** [comment]
Hi,

Any updates on the issue?

**Comment by kidtsunami** [comment]
Can you provide what proxy details you have or firewall settings?

**Comment by mKirti** [comment]
@kidtsunami I am afraid i cannot share the details. But yes i am behind a proxy setting.

i am getting the below when i try to give the settings in HTTPS_PROXY setting.

**tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 2010 2010:80**

**Comment by mKirti** [comment]
@kidtsunami Please find below the logs info while creating a new project:

2017-02-21T09:01:13.960Z - info: initiated client:  {"name":"mavensmate-app","isServer":true,"isNodeApp":false,"isCommandLine":false,"settings":{"type":"literal"}}
2017-02-21T09:01:22.538Z - debug: Processing request GET for URL: /app/home/index
2017-02-21T09:05:07.795Z - debug: Processing request GET for URL: /app/settings/index
2017-02-21T09:05:09.017Z - debug: query params v=3.1.0
2017-02-21T09:05:23.122Z - debug: Processing request POST for URL: /app/settings/update
2017-02-21T09:05:23.123Z - debug: post body settingValue=INFO, settingKey=mm_log_level
2017-02-21T09:05:30.133Z - debug: Processing request GET for URL: /app/project/new
2017-02-21T09:05:31.432Z - debug: query params v=3.1.0
2017-02-21T09:05:58.936Z - debug: Processing request POST for URL: /app/project/create
2017-02-21T09:05:58.937Z - debug: post body name=TestProject, username=*****@*****.com, password=*****, orgType=developer, ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*, StaticResource=*, workspace=C:\Users\int_cvtest10\Desktop\MavensMate_Workspace, action=new, loginUrl=
2017-02-21T09:05:58.940Z - debug: received request to create new project: 
2017-02-21T09:05:58.941Z - debug:  name=TestProject, username=*****@*****.com, password=*****, orgType=developer, ApexClass=*, ApexComponent=*, ApexPage=*, ApexTrigger=*, StaticResource=*, workspace=C:\Users\int_cvtest10\Desktop\MavensMate_Workspace, action=new, loginUrl=
2017-02-21T09:05:58.942Z - info: 

==================> executing command: new-project

2017-02-21T09:05:58.942Z - debug: executeCommand payload is: {"name":"TestProject","username":"*****@*****.com","password":"*****","orgType":"developer","package":{"ApexClass":"*","ApexComponent":"*","ApexPage":"*","ApexTrigger":"*","StaticResource":"*"},"workspace":"C:\\Users\\int_cvtest10\\Desktop\\MavensMate_Workspace","action":"new","loginUrl":""}
2017-02-21T09:05:58.942Z - debug: command class is: NewProjectCommand
2017-02-21T09:05:58.944Z - debug: initiating SalesforceClient: 
2017-02-21T09:05:58.945Z - debug: initializing connection to salesforce ...
2017-02-21T09:05:58.946Z - debug: logging in to salesforce: https://login.salesforce.com/
2017-02-21T09:05:59.686Z - debug: Processing request GET for URL: /status?id=f5de26b0-f814-11e6-853f-a772ae0f85cc
2017-02-21T09:05:59.686Z - debug: query params id=f5de26b0-f814-11e6-853f-a772ae0f85cc
2017-02-21T09:06:02.253Z - debug: error logging in: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 2010 2010:80
2017-02-21T09:06:02.255Z - debug: Could not create project: 
2017-02-21T09:06:02.257Z - debug: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 2010 2010:80
    at ClientRequest.onError (C:\ProgramData\App-V\57E7E720-3C18-4396-8D7F-129ADB83C74F\D582CCE8-EA8D-4A25-BDFD-8B6E910B87D6\Root\resources\app\node_modules\jsforce\node_modules\tunnel-agent\index.js:174:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:978:8)
    at doNTCallback2 (node.js:438:9)
    at process._tickCallback (node.js:352:17)
2017-02-21T09:06:02.258Z - info: handling command result: 
2017-02-21T09:06:02.258Z - error:  Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 2010 2010:80
    at ClientRequest.onError (C:\ProgramData\App-V\57E7E720-3C18-4396-8D7F-129ADB83C74F\D582CCE8-EA8D-4A25-BDFD-8B6E910B87D6\Root\resources\app\node_modules\jsforce\node_modules\tunnel-agent\index.js:174:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:978:8)
    at doNTCallback2 (node.js:438:9)
    at process._tickCallback (node.js:352:17)
2017-02-21T09:06:02.259Z - debug: finishing jobid: f5de26b0-f814-11e6-853f-a772ae0f85cc
2017-02-21T09:06:02.259Z - error:  Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 2010 2010:80
    at ClientRequest.onError (C:\ProgramData\App-V\57E7E720-3C18-4396-8D7F-129ADB83C74F\D582CCE8-EA8D-4A25-BDFD-8B6E910B87D6\Root\resources\app\node_modules\jsforce\node_modules\tunnel-agent\index.js:174:17)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:978:8)
    at doNTCallback2 (node.js:438:9)
    at process._tickCallback (node.js:352:17)
2017-02-21T09:06:02.710Z - debug: Processing request GET for URL: /status?id=f5de26b0-f814-11e6-853f-a772ae0f85cc
2017-02-21T09:06:02.710Z - debug: query params id=f5de26b0-f814-11e6-853f-a772ae0f85cc

**Comment by kidtsunami** [comment]
Yeah definitely looks like a Proxy/Firewall issue, you'll need the assistance of the network admin who set up the Proxy/Firewall to resolve.

**Comment by mKirti** [comment]
@kidtsunami i configured the HTTPS_PROXY in the settings. The same proxy settings are working for other apps in the client network. Is there anything specific required for MavensMate. I have sent you the logs above.

**Comment by kidtsunami** [comment]
@mKirti MavensMate Desktop has no dependency on the Sublime Text plugin, so that shouldn't affect this/cause any issues.

There shouldn't be anything specific required for MavensMate. I'll have a look, but as I didn't build the HTTPS_PROXY element of MavensMate, I'm a bit behind and may not be able to resolve this.

**Comment by mKirti** [comment]
@kidtsunami Hi. I was able to fix the issue by only configuring the **http_proxy** setting. It is somehow not supporting **https_proxy** setting.

Thanks for your support. :)

**Comment by kidtsunami** [comment]
Haha wow! Thanks for sharing. I'll tag this issue so we can hopefully help others.
