### ISSUE TITLE
"[ERROR]: Could not update lightning components: Cannot read property 'Id' of undefined" when uploading Lighting JS Controller File from Sublime Text

### ISSUE THREAD

**Issue by dylanribb** [joeferraro/MavensMate#957]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: Sublime Text 3 build 3126 (stable)

* **MavensMate Plugin Version**: 7.0.2

* **Platform/Version**: Windows 10 64-bit

* **Proxy Details**: N/A

* **Salesforce API Version**: 39.0

* **Salesforce Server**: Custom Dev/Testing Org

1. Create a new Lightning Component in the Developer Console within Salesfore.
2. Generate a JS controller for the Component.
3. Download component/JS files from Salesforce using MavensMate.
4. Make a change to the JS controller file.
5. Hit Save (CTRL+S), observe error.

This seems be working fine for Components created using MavensMate, but not for ones that were originally created within the Salesforce Developer Console.

**Comment by TomSesselmann** [comment]
I'm getting this on my Mac as well. When I try to drag a new component in to my Aura folder from a third party vendor i.e. https://github.com/appiphony/Strike-Components then the deleting .lightning file trick doesn't work either.

**Comment by Ynozzar** [comment]
Happens the same to me on Atom (plugin version 1.0.10) and with the same MavensMate Desktop version as OP. SF API is 39.0, and SO is W7 x64. Also in a Dev Org. When using VSCode (Plugin 0.7.0), it doesn't give any error message, but doesn't update the code either.

Here's Atom error log (I replaced ID values with 'xxxxxxx'):
`{
  "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "complete": true,
  "error": "Could not update lightning components: Cannot read property 'Id' of undefined",
  "stack": "Error: Could not update lightning components: Cannot read property 'Id' of undefined\n    at C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\app\\lib\\services\\lightning.js:188:18\n    at tryCatch1 (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\util.js:45:21)\n    at Promise._callHandler (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:571:13)\n    at Promise._settlePromiseFromHandler (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:581:18)\n    at Promise._settlePromiseAt (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:733:18)\n    at Promise._settlePromises (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:845:14)\n    at Async._consumeFunctionBuffer (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:85:12)\n    at Async.consumeFunctionBuffer (C:\\Users\\626789\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:40:14)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)",
  "promiseId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}`

**Comment by wirefly09** [comment]
I am getting this error as well. 

MavensMate Desktop Version: v0.0.11-beta.7
Editor: Sublime Text 3 build 3126
MavensMate Plugin Version: 7.0.2
Platform/Version: Windows 10 64-bit
Salesforce API Version: 39.0
Salesforce Server: Custom Dev/Testing Org

Operation: Compiling: C:\Users\mark_\Documents\Projects\SFDC\TriFin Labs Demo\src\aura\helloMessage\helloMessage.cmp
Timestamp: Tue, 08 Aug 2017 11:37:22
   Result: [ERROR]: Could not update lightning components: Cannot read property 'Id' of undefined

[MAVENSMATE]: =============> Starting MavensMate for Sublime Text
SublimeSalesforceReference: Startup caching will begin shortly
Package Control: Skipping automatic upgrade, last run at 2017-08-08 10:50:33, next run at 2017-08-08 11:50:33 or after
Check to see if this an aura thingy.
Check to see if the file ends in .JS. C:\Users\mark_\Documents\Projects\SFDC\TriFin Labs Demo\src\aura\helloMessage\helloMessage.cmp
Running force aura push -f 'C:\Users\mark_\Documents\Projects\SFDC\TriFin Labs Demo\src\aura\helloMessage\helloMessage.cmp'
[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: compile-metadata
[MAVENSMATE]: {'context': <sublime.View object at 0x000001BFBDB90080>, 'body': {'paths': ['C:\\Users\\mark_\\Documents\\Projects\\SFDC\\TriFin Labs Demo\\src\\aura\\helloMessage\\helloMessage.cmp']}}
[MAVENSMATE]: http://localhost:56248/execute?command=compile-metadata&async=1&pid=21220ca0-56ad-11e7-a07a-a947dcbfa00d
[MAVENSMATE]: posting to MavensMate:
[MAVENSMATE]: b'{"paths": ["C:\\\\Users\\\\mark_\\\\Documents\\\\Projects\\\\SFDC\\\\TriFin Labs Demo\\\\src\\\\aura\\\\helloMessage\\\\helloMessage.cmp"]}'
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x000001BFBDB90C88>
[MAVENSMATE]: {'error': "Could not update lightning components: Cannot read property 'Id' of undefined", 'id': '94b8d050-7c4f-11e7-b193-4310ac5ab1f8', 'complete': True, 'stack': "Error: Could not update lightning components: Cannot read property 'Id' of undefined\n    at C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\app\\lib\\services\\lightning.js:188:18\n    at tryCatch1 (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\util.js:45:21)\n    at Promise._callHandler (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:571:13)\n    at Promise._settlePromiseFromHandler (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:581:18)\n    at Promise._settlePromiseAt (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:733:18)\n    at Promise._settlePromises (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:845:14)\n    at Async._consumeFunctionBuffer (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:85:12)\n    at Async.consumeFunctionBuffer (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:40:14)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}
[MAVENSMATE]: Could not load json response from mavensmate
[MAVENSMATE]: {'error': "Could not update lightning components: Cannot read property 'Id' of undefined", 'id': '94b8d050-7c4f-11e7-b193-4310ac5ab1f8', 'complete': True, 'stack': "Error: Could not update lightning components: Cannot read property 'Id' of undefined\n    at C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\app\\lib\\services\\lightning.js:188:18\n    at tryCatch1 (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\util.js:45:21)\n    at Promise._callHandler (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:571:13)\n    at Promise._settlePromiseFromHandler (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:581:18)\n    at Promise._settlePromiseAt (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:733:18)\n    at Promise._settlePromises (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\promise.js:845:14)\n    at Async._consumeFunctionBuffer (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:85:12)\n    at Async.consumeFunctionBuffer (C:\\Users\\mark_\\AppData\\Local\\MavensMate\\app-0.0.11-beta7\\resources\\app\\node_modules\\mavensmate\\node_modules\\bluebird\\js\\main\\async.js:40:14)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickCallback (internal/process/next_tick.js:98:9)"}

**Comment by inakirzabalegui** [comment]
Same for me. If the component is not created through mavensmate then it has an error when trying to upload to the server. Did anybody figure out a workaround?

**Comment by cnaccio** [comment]
Also having this issue on Windows 10 x64

**Comment by e-bacho** [comment]
Deleting the `.lightning` file from the `config` folder seems to be working...

**Comment by pogilvie** [comment]
Thank you so much folks!   Yes deleting .lightning worked.   Just to be complete I shutdown atom and mavensmate restarted mavensmake refreshed metedata index and project then re-opened atom.

**Comment by kylewalke** [comment]
Worked for me too. Upon saving in VS Code it regenerated the .lightning file without the errors.

**Comment by kentavros** [comment]
But when you will create some controller, or helper in Maven and save it on org (pressed CTRL+S) you will got this error to:
[ERROR]		Compile File: Failed
Could not update lightning components: Cannot read property 'Id' of undefined
And deleting the .lightning file from the config folder doesn't work! (((((

**Comment by fedegiust** [comment]
Worked for me after deleting the .lightning file and restarting vs code

**Comment by fedegiust** [comment]
+1

Deleting the .lightning doesn't work
It seems that it's missing the metadata api callouts to create this lightning components

**Comment by fedegiust** [comment]
The only workaround I've found is create the controller/helper in the developer console and then refresh the project in mavensmate
