### ISSUE TITLE
[STATUS]	Open UI: Starting [ERROR]		Open UI: Error: connect ECONNREFUSED 127.0.0.1:56248 RequestError: Error: connect ECONNREFUSED 127.0.0.1:56248

### ISSUE THREAD

**Issue by jbawgs** [joeferraro/MavensMate#964]
0.0.11-beta7

VSCode

0.7.0

Mint 18

No proxy/Firewall
--------------------------------------

Wanting to try out the product, and I'm sure I'm simply missing something simple... but when I issue a command (most just cause a popup saying that I need an open project) like Open UI or New Project, I get:

[STATUS]	MavensMate: Activating
[STATUS]	Instantiating without Project
[STATUS]	New Project: Starting
[ERROR]		New Project: Error: connect ECONNREFUSED 127.0.0.1:56248
RequestError: Error: connect ECONNREFUSED 127.0.0.1:56248
    at new RequestError (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request/request.js:824:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[STATUS]	New Project: Starting
[ERROR]		New Project: Error: connect ECONNREFUSED 127.0.0.1:56248
RequestError: Error: connect ECONNREFUSED 127.0.0.1:56248
    at new RequestError (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request/request.js:824:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[STATUS]	Open UI: Starting
[ERROR]		Open UI: Error: connect ECONNREFUSED 127.0.0.1:56248
RequestError: Error: connect ECONNREFUSED 127.0.0.1:56248
    at new RequestError (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/home/boggs/.vscode/extensions/DavidHelmer.mavensmate-0.7.0/node_modules/request/request.js:824:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by thelastaghori** [comment]
I was getting the same error, You should try opening up the mavensmate app and make sure you're connected via the mavensmate app. Once that is done, you should be able to cmd+shift+p to mavensmate and refresh/reload etc.
