### ISSUE TITLE
Javascript error while "Refresh File From Server"

### ISSUE THREAD

**Issue by haripopuri** [joeferraro/MavensMate#980]
* **MavensMate Desktop Version**:
v0.0.11-beta.7

* **Editor**:
Submile

* **MavensMate Plugin Version**:
7.0.2

* **Platform/Version**:
OS X

* **Proxy Details**:

* **Salesforce API Version**:
37

* **Salesforce Server**:
cs63

I made change in salesforce through clicks (config change) and refreshing metadata file in Sublime.
Right click on component and select "Refresh File From Server".
It was working file until few hours back.

**Could not extract and write stream to file system.**

Uncaught Exception:
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:259:9)
    at Function.Buffer.from (buffer.js:96:10)
    at new Buffer (buffer.js:75:17)
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/mavensmate/app/lib/sfdc-client.js:825:34
    at /Applications/MavensMate.app/Contents/Resources/app/node_modules/jsforce/lib/promise.js:72:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by gmax7** [comment]
I have the exact same error message (same versions of Sublime and MavensMate, as well).  It happens when I try to edit the project metadata to include Report and ReportType and then click Update Project.  If I deselect those two metadata types and then update the project, there is no error message and the operations completes fine.  Screenshot attached.
![mavensmate](https://user-images.githubusercontent.com/29614362/27407289-c38eb75c-56a5-11e7-9884-bd82d6c99aa5.png)

**Comment by DougMidgley** [comment]
Same error with me, basically with all Metadata types tho :(
